/**
 * Digital Business Execution (₹8,000) — 24-file Business Execution Toolkit.
 * Each resource is generated as a PDF and stored in Convex.
 */

export interface BusinessResourceDef {
  title: string;
  slug: string;
  type: "pdf";
  description: string;
  sortOrder: number;
  pdfLines: string[];
}

export const BUSINESS_RESOURCES: BusinessResourceDef[] = [
  // ── Software & Tools (1) ────────────────────────────────────
  {
    title: "Tools & Software Stack Guide",
    slug: "tools-software-stack-guide",
    type: "pdf",
    description:
      "The recommended free and paid stack for every function: websites, email, WhatsApp, CRM, design, ads, analytics, AI.",
    sortOrder: 1,
    pdfLines: [
      "TOOLS & SOFTWARE STACK GUIDE",
      "ZetaGrow Business Execution Toolkit | File 1 of 24",
      "",
      "WEBSITES & LANDING PAGES",
      "  - Website: Next.js / WordPress / Framer",
      "  - Landing pages: Framer / Carrd / WordPress page builder",
      "  - Forms: built-in or Google Forms / Typeform (free tiers)",
      "",
      "EMAIL",
      "  - Free starter: Gmail + Google Workspace",
      "  - Sequences: Mailchimp / Brevo free tiers (limited sends)",
      "",
      "WHATSAPP (India-first)",
      "  - WhatsApp Business app (free, manual)",
      "  - WhatsApp Business API via platform partners (automated)",
      "  - Saved reply templates for instant responses",
      "",
      "CRM",
      "  - Starter: spreadsheet (up to ~50 leads)",
      "  - Growing: free tiers of HubSpot / Zoho CRM",
      "",
      "DESIGN & CREATIVE",
      "  - Canva free (social creatives, PDFs)",
      "  - CapCut (reels/editing), phone camera for UGC",
      "",
      "ADS PLATFORMS",
      "  - Meta: Business Portfolio + Ads Manager + Pixel",
      "  - Google: Ads account + Search Console + Tag",
      "",
      "ANALYTICS",
      "  - Platform insights (Meta/Google) first",
      "  - Google Analytics 4 for website behavior",
      "  - Your own KPI tracker (see calculators)",
      "",
      "AI TOOLS",
      "  - Chat assistants for drafting (ChatGPT/Claude/Gemini)",
      "  - Image: Canva AI / free image generators",
      "  - Video: CapCut AI features",
      "",
      "PAYMENTS (India)",
      "  - UPI (PhonePe/GPay) + Razorpay/Instamojo for checkouts",
      "  - Invoices: free tools or simple templates",
      "",
      "RULE: Start free, add tools only when a bottleneck proves itself.",
    ],
  },
  // ── AI Business Toolkit (3) ─────────────────────────────────
  {
    title: "AI Research Prompts",
    slug: "ai-research-prompts",
    type: "pdf",
    description:
      "Ready-to-use prompts for customer research, competitor analysis, market gaps, and pricing research.",
    sortOrder: 2,
    pdfLines: [
      "AI RESEARCH PROMPTS",
      "ZetaGrow Business Execution Toolkit | File 2 of 24",
      "",
      "CUSTOMER RESEARCH",
      "  \"Here are 20 customer reviews from [competitor]. List the",
      "  top 5 pains in the customers' own words, with how many",
      "  reviews mention each pain.\"",
      "  \"I interviewed 5 customers about [problem]. Here are my",
      "  notes: [notes]. Write a one-paragraph problem statement",
      "  using only their words and feelings.\"",
      "",
      "PERSONA BUILDING",
      "  \"Build an Ideal Customer Profile for [offer]. Include:",
      "  demographics, goals, surface pain, root pain, emotional",
      "  pain, objections, where they hang out online. Be specific,",
      "  not generic.\"",
      "",
      "COMPETITOR ANALYSIS",
      "  \"Here is what my 3 competitors sell and how they price:",
      "  [data]. For each, list: offer, price, positioning, 2",
      "  strengths, 2 weaknesses. Then identify 3 market gaps.\"",
      "",
      "MARKET GAP SEARCH",
      "  \"For [niche], list segments competitors serve poorly:",
      "  geography, language, audience level, format, price tier.",
      "  For each gap: evidence demand exists, and how a",
      "  beginner could enter it.\"",
      "",
      "INTERVIEW GUIDE",
      "  \"Write a 15-minute customer interview guide for",
      "  [problem]. Include: warm-up, their last attempt, costs of",
      "  the problem, desired outcome, willingness to pay, and a",
      "  closing question.\"",
      "",
      "FACT-CHECK RULE",
      "  Add to every prompt: 'Mark any statement you are not",
      "  certain about. Do not invent numbers.'",
      "",
      "RULE: Give AI raw material (reviews, notes, data), not a",
      "blank page, and always review its output.",
    ],
  },
  {
    title: "AI Content & Marketing Workflows",
    slug: "ai-content-marketing-workflows",
    type: "pdf",
    description:
      "Step-by-step AI workflows for hooks, ad copy, landing pages, emails, and weekly content plans.",
    sortOrder: 3,
    pdfLines: [
      "AI CONTENT & MARKETING WORKFLOWS",
      "ZetaGrow Business Execution Toolkit | File 3 of 24",
      "",
      "WORKFLOW 1 - WEEKLY CONTENT PLAN",
      "  Trigger: Sunday planning.",
      "  Prompt: \"Given my pillars [list], produce 10 content",
      "  ideas for [audience], each with a hook line and one",
      "  takeaway. Avoid hype words.\"",
      "  Review: pick the 5 you can genuinely teach. Schedule.",
      "",
      "WORKFLOW 2 - HOOKS",
      "  Prompt: \"Write 10 hooks about [topic] for [audience].",
      "  Mix: curiosity, emotion, number, pattern interrupt.",
      "  Max 10 words each.\"",
      "  Review: keep 3, test them in reels.",
      "",
      "WORKFLOW 3 - AD COPY VARIATIONS",
      "  Prompt: \"Here is my winning ad [copy]. Write 5",
      "  variations changing only the hook. Keep the offer and",
      "  CTA identical.\"",
      "  Review: check honesty and tone, then test.",
      "",
      "WORKFLOW 4 - LANDING PAGE DRAFT",
      "  Prompt: \"Draft a landing page for [offer] for",
      "  [audience]. Sections: headline, subheadline, proof,",
      "  problem, solution, objections FAQ, offer, CTA. Use",
      "  benefit-led language.\"",
      "  Review: apply your Landing Page Checklist.",
      "",
      "WORKFLOW 5 - EMAIL SEQUENCE",
      "  Prompt: \"Write a 4-email sequence for new leads from",
      "  [lead magnet]. Email 1: welcome + deliverable. Email 2:",
      "  value. Email 3: proof. Email 4: offer with one CTA.\"",
      "  Review: personal tone, one goal per email.",
      "",
      "WORKFLOW 6 - REVISE IN YOUR VOICE",
      "  Prompt: \"Rewrite this in a direct, friendly, no-hype",
      "  voice: [draft].\" Then edit yourself - the final pass is",
      "  always human.",
      "",
      "RULE: AI drafts 80%, you own the final 20%.",
    ],
  },
  {
    title: "AI Operations & Automation Playbook",
    slug: "ai-operations-automation-playbook",
    type: "pdf",
    description:
      "Automate lead replies, tagging, support, and reporting with AI workflows: trigger, prompt, output, review.",
    sortOrder: 4,
    pdfLines: [
      "AI OPERATIONS & AUTOMATION PLAYBOOK",
      "ZetaGrow Business Execution Toolkit | File 4 of 24",
      "",
      "THE WORKFLOW PATTERN",
      "  Every automation = Trigger + Prompt + Output + Review.",
      "  Automate the drafting, never the judgment.",
      "",
      "AUTOMATION 1 - LEAD REPLY DRAFTING",
      "  Trigger: new form/WhatsApp lead.",
      "  Prompt: \"Draft a reply to this lead using their answers:",
      "  [form data]. Acknowledge their specific interest, answer",
      "  their question, suggest one next step. Max 60 words.\"",
      "  Output: drafted message + suggested tag.",
      "  Review: human approves before send (or the message",
      "  template is pre-approved).",
      "",
      "AUTOMATION 2 - LEAD TAGGING",
      "  Trigger: form answer contains keywords.",
      "  Prompt: \"Classify this lead: fit (1-3), intent (1-3),",
      "  timing (1-3). Output one recommended action: sales",
      "  today / nurture / newsletter.\"",
      "  Output: score + action.",
      "  Review: spot-check 10% weekly.",
      "",
      "AUTOMATION 3 - SUPPORT TICKET DRAFTING",
      "  Trigger: support message about a known topic.",
      "  Prompt: \"Draft a reply using only our policy: [policy",
      "  text]. If the question is not covered, say so.\"",
      "  Output: draft reply + escalate flag.",
      "  Review: complex cases always go to a human.",
      "",
      "AUTOMATION 4 - DAILY REPORT SUMMARY",
      "  Trigger: end of day.",
      "  Prompt: \"Summarize this data: [numbers]. Flag anything",
      "  above or below threshold, and propose one action.\"",
      "  Output: 5-line daily summary.",
      "  Review: Monday deep review with the diagnostic",
      "  framework.",
      "",
      "SAFETY RULES",
      "  - Never let AI promise refunds, prices, or policies it",
      "    does not know.",
      "  - Add 'flag anything uncertain' to every prompt.",
      "  - Keep a human on every customer-facing output until",
      "    the template is battle-tested.",
      "",
      "RULE: One boring repetitive task at a time. Then the next.",
    ],
  },
  // ── Marketing Templates (3) ─────────────────────────────────
  {
    title: "Customer Persona Template",
    slug: "customer-persona-template",
    type: "pdf",
    description:
      "The full ICP worksheet: demographics, goals, surface/root/emotional pains, objections, and channels.",
    sortOrder: 5,
    pdfLines: [
      "CUSTOMER PERSONA TEMPLATE",
      "ZetaGrow Business Execution Toolkit | File 5 of 24",
      "",
      "PERSONA NAME: ______________________________",
      "",
      "DEMOGRAPHICS",
      "  Age: ____________  Gender: ____________",
      "  Location: ____________  Income: ____________",
      "  Role / business: ________________________",
      "",
      "GOALS",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "PAINS (in the customer's own words)",
      "  Surface pain: ____________________________",
      "  Root pain: ______________________________",
      "  Emotional pain: __________________________",
      "",
      "WHAT FAILURE COSTS THEM",
      "  Time: ____________  Money: Rs. ____________",
      "  Status/emotion: __________________________",
      "",
      "OBJECTIONS",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "CHANNELS",
      "  [ ] Instagram  [ ] YouTube  [ ] WhatsApp",
      "  [ ] Google search  [ ] LinkedIn  [ ] Communities",
      "",
      "BUYING TRIGGERS",
      "  What event makes them buy NOW? ______________",
      "",
      "ONE-SENTENCE PROFILE",
      "  \"________ is a ________ who wants ________",
      "  but struggles with ________.\"",
      "",
      "RULE: One persona per offer. Research language, don't",
      "invent it.",
    ],
  },
  {
    title: "Funnel Planner",
    slug: "funnel-planner",
    type: "pdf",
    description:
      "Design all 7 funnel stages with one job and one metric each, plus the leak to fix first.",
    sortOrder: 6,
    pdfLines: [
      "FUNNEL PLANNER",
      "ZetaGrow Business Execution Toolkit | File 6 of 24",
      "",
      "STAGE 1 - CONTENT",
      "  Channels: ______________________________",
      "  Cadence: ______________________________",
      "  Metric: ______________________________",
      "",
      "STAGE 2 - TRAFFIC",
      "  Sources: [ ] Meta  [ ] Google  [ ] Organic",
      "  Budget: Rs. ______  Metric: ______________",
      "",
      "STAGE 3 - LANDING PAGE",
      "  URL: ________________________________",
      "  Promise (headline): ____________________",
      "  Metric: ______________________________",
      "",
      "STAGE 4 - LEAD",
      "  Lead magnet: __________________________",
      "  Form fields: __________________________",
      "  Metric: ______________________________",
      "",
      "STAGE 5 - FOLLOW-UP",
      "  Speed target: ______ minutes",
      "  Sequence: ____________________________",
      "  Metric: ______________________________",
      "",
      "STAGE 6 - SALE",
      "  Offer: ______________________________",
      "  Checkout: ____________________________",
      "  Metric: ______________________________",
      "",
      "STAGE 7 - RETENTION",
      "  Onboarding: __________________________",
      "  Review ask: ____________  Referral: ____________",
      "  Metric: ______________________________",
      "",
      "BIGGEST LEAK THIS MONTH (fix first)",
      "  ________________________________________",
      "",
      "RULE: Fix the biggest leak before adding more traffic.",
    ],
  },
  {
    title: "Offer Builder",
    slug: "offer-builder",
    type: "pdf",
    description:
      "Build the complete honest offer: outcome, package, price with anchor, bonuses, guarantee, urgency, positioning.",
    sortOrder: 7,
    pdfLines: [
      "OFFER BUILDER",
      "ZetaGrow Business Execution Toolkit | File 7 of 24",
      "",
      "1. SPECIFIC OUTCOME",
      "  The measured result the customer gets:",
      "  \"________________________________________\"",
      "  Timeline: ______________________________",
      "",
      "2. PACKAGE",
      "  Main deliverable: ________________________",
      "  Supporting elements: ____________________",
      "  Package name: __________________________",
      "",
      "3. PRICING",
      "  Price: Rs. ______  Anchor: Rs. ______",
      "  Tiers: Basic Rs. ____ / Standard Rs. ____ /",
      "  Premium Rs. ____",
      "",
      "4. BONUSES (must support the outcome)",
      "  1. ____________________________________",
      "  2. ____________________________________",
      "  3. ____________________________________",
      "",
      "5. GUARANTEE",
      "  What risk it removes: ____________________",
      "  Terms: ________________________________",
      "",
      "6. URGENCY (honest only)",
      "  Deadline / spots / launch terms: ______________",
      "",
      "7. POSITIONING SENTENCE",
      "  \"For [customer], [offer] is the [category] that",
      "  [outcome], unlike [alternative], because [reason].\"",
      "",
      "8. OFFER STATEMENT (one paragraph)",
      "  \"For Rs. ______, [customer] gets ____________,",
      "  plus ____________, protected by ____________,",
      "  until ____________.\"",
      "",
      "HONESTY CHECK",
      "  [ ] Every claim can be backed by proof",
      "  [ ] No hype words in the final statement",
      "",
      "RULE: If it fits one paragraph and passes the honesty",
      "check, the offer is ready to market.",
    ],
  },
  // ── Meta/Google Campaign Templates (2) ──────────────────────
  {
    title: "Meta Ads Campaign Planner",
    slug: "meta-ads-campaign-planner",
    type: "pdf",
    description:
      "Advanced Meta campaign planner: objective, audiences, budget split, creative matrix, tracking, and decision rules.",
    sortOrder: 8,
    pdfLines: [
      "META ADS CAMPAIGN PLANNER",
      "ZetaGrow Business Execution Toolkit | File 8 of 24",
      "",
      "CAMPAIGN NAME: ______________________________",
      "  (Platform-Objective-Audience-Creative-Offer)",
      "",
      "1. OBJECTIVE (one only)",
      "  [ ] Sales  [ ] Leads  [ ] Traffic  [ ] Awareness",
      "",
      "2. AUDIENCES",
      "  Cold: [ ] Broad  [ ] Interest: ____________",
      "  Warm: [ ] Video 50%  [ ] Engaged  [ ] Visitors",
      "  Hot:  [ ] Cart  [ ] Checkout  [ ] Purchasers",
      "  Exclusions: ______________________________",
      "",
      "3. BUDGET ALLOCATION",
      "  Total: Rs. ______",
      "  Cold 50-60%: Rs. ______",
      "  Retarget 20-30%: Rs. ______",
      "  Testing 10-20%: Rs. ______",
      "",
      "4. CREATIVE MATRIX",
      "  Hooks: 1.____________ 2.____________ 3.____________",
      "  Formats: 1.____________ 2.____________ 3.____________",
      "  Offers: 1.____________ 2.____________",
      "  Combos to test: ______________________________",
      "",
      "5. TRACKING",
      "  Pixel installed: [ ]  Events verified: [ ]",
      "  Key events: ______________________________",
      "",
      "6. DECISION RULES (set BEFORE launch)",
      "  Kill if: CTR < ____% or CPA > Rs. ______ after 5 days.",
      "  Scale if: CPA < Rs. ______ for 3 days (raise 20-30%).",
      "  Review date: ____________",
      "",
      "RULE: Budget follows strategy; decisions are written",
      "before the campaign starts.",
    ],
  },
  {
    title: "Google Ads Campaign Planner",
    slug: "google-ads-campaign-planner",
    type: "pdf",
    description:
      "Advanced Google Ads planner: intent tiers, keyword groups, negatives, structure, search-terms ritual, tracking.",
    sortOrder: 9,
    pdfLines: [
      "GOOGLE ADS CAMPAIGN PLANNER",
      "ZetaGrow Business Execution Toolkit | File 9 of 24",
      "",
      "CAMPAIGN NAME: ______________________________",
      "",
      "1. INTENT TIERS",
      "  Transactional keywords (buy now):",
      "    - ____________________  - ____________________",
      "  Commercial keywords (compare):",
      "    - ____________________  - ____________________",
      "  (Informational goes to content, not ads)",
      "",
      "2. AD GROUPS (one theme each, 5-15 keywords)",
      "  Group 1: ______________________________",
      "    Keywords: __________________________",
      "  Group 2: ______________________________",
      "    Keywords: __________________________",
      "",
      "3. NEGATIVE KEYWORDS",
      "  - free  - job  - salary  - tutorial",
      "  - ____________________  - ____________________",
      "",
      "4. MATCH TYPES",
      "  Testing phase: exact only",
      "  Scale phase: phrase + exact, negatives updated",
      "",
      "5. LANDING PAGE RELEVANCE",
      "  URL: ________________________________",
      "  Headline matches ad promise: [ ]  Price visible: [ ]",
      "  One CTA: [ ]",
      "",
      "6. CONVERSION TRACKING",
      "  Conversion actions set: [ ]  Values assigned: [ ]",
      "",
      "7. WEEKLY SEARCH-TERMS RITUAL",
      "  [ ] Export search terms report (every Monday)",
      "  [ ] Promote converting terms to exact",
      "  [ ] Add irrelevant terms as negatives",
      "",
      "RULE: The search terms report is the truth of your",
      "account. Review it weekly, always.",
    ],
  },
  // ── SEO Resources (2) ───────────────────────────────────────
  {
    title: "Keyword Research Worksheet",
    slug: "keyword-research-worksheet",
    type: "pdf",
    description:
      "Find and classify keywords by intent, spot long-tail opportunities, and pick your monthly priorities.",
    sortOrder: 10,
    pdfLines: [
      "KEYWORD RESEARCH WORKSHEET",
      "ZetaGrow Business Execution Toolkit | File 10 of 24",
      "",
      "TOPIC: ______________________________",
      "",
      "KEYWORD TABLE",
      "  | Keyword | Intent I/C/T | Volume est. | Priority |",
      "  |---------|--------------|-------------|----------|",
      "  |         |              |             |          |",
      "  |         |              |             |          |",
      "  |         |              |             |          |",
      "  |         |              |             |          |",
      "  |         |              |             |          |",
      "",
      "INTENT KEY",
      "  I = Informational -> blog content",
      "  C = Commercial -> comparison + ads",
      "  T = Transactional -> product pages + ads",
      "",
      "LONG-TAIL OPPORTUNITIES (winnable)",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "  4. ________________________________________",
      "  5. ________________________________________",
      "",
      "SOURCES",
      "  [ ] Google autocomplete  [ ] People Also Ask",
      "  [ ] Competitor pages     [ ] Search Console",
      "",
      "MONTHLY PRIORITIES",
      "  1. ________________ (content type: ________)",
      "  2. ________________ (content type: ________)",
      "  3. ________________ (content type: ________)",
      "",
      "RULE: Long-tail first, intent-matched pages, one cluster",
      "per month.",
    ],
  },
  {
    title: "SEO Content & Cluster Planner",
    slug: "seo-content-cluster-planner",
    type: "pdf",
    description:
      "Plan content pillars and a full topic cluster with internal linking, plus the repurposing chain.",
    sortOrder: 11,
    pdfLines: [
      "SEO CONTENT & CLUSTER PLANNER",
      "ZetaGrow Business Execution Toolkit | File 11 of 24",
      "",
      "PILLARS (3-5)",
      "  1. ______________________________",
      "  2. ______________________________",
      "  3. ______________________________",
      "  4. ______________________________",
      "  5. ______________________________",
      "",
      "CLUSTER TOPIC: ______________________________",
      "  Pillar page URL: __________________________",
      "  Pillar keyword: __________________________",
      "",
      "SUPPORTING ARTICLES",
      "  1. Title: ________________ | Keyword: ____________",
      "  2. Title: ________________ | Keyword: ____________",
      "  3. Title: ________________ | Keyword: ____________",
      "  4. Title: ________________ | Keyword: ____________",
      "  5. Title: ________________ | Keyword: ____________",
      "  (Each links UP to the pillar page)",
      "",
      "REPURPOSING CHAIN (one core piece)",
      "  Core piece: ______________________________",
      "  1. Shorts/reels: ______ 2. Quotes/carousels: ______",
      "  3. Thread: ________ 4. Email: ________",
      "  5. FAQ update: ________ 6. Community post: ________",
      "",
      "ON-PAGE REMINDER",
      "  [ ] Title (keyword first, <60 chars)",
      "  [ ] Meta description (155 chars, benefit + CTA)",
      "  [ ] One H1 + logical H2/H3",
      "  [ ] Answer fully in the first paragraph",
      "  [ ] Image alt text with keyword",
      "",
      "RULE: One idea, six pieces. Depth beats volume.",
    ],
  },
  // ── Landing Page Templates (3) ──────────────────────────────
  {
    title: "Landing Page Structure Template",
    slug: "landing-page-structure-template",
    type: "pdf",
    description:
      "The 9-section high-converting landing page skeleton with fill-in blocks for each section.",
    sortOrder: 12,
    pdfLines: [
      "LANDING PAGE STRUCTURE TEMPLATE",
      "ZetaGrow Business Execution Toolkit | File 12 of 24",
      "",
      "URL: ______________________________  GOAL: ____________",
      "",
      "SECTION 1 - HEADLINE (the promise, matches the ad)",
      "  \"________________________________________\"",
      "",
      "SECTION 2 - SUBHEADLINE (expands the promise)",
      "  \"________________________________________\"",
      "",
      "SECTION 3 - HERO VISUAL",
      "  Show: product / result / demo thumbnail",
      "  Note: ______________________________",
      "",
      "SECTION 4 - PROOF (early!)",
      "  Numbers: ______________________________",
      "  Testimonial: __________________________",
      "",
      "SECTION 5 - PROBLEM (in their words)",
      "  \"________________________________________\"",
      "",
      "SECTION 6 - SOLUTION (benefits first)",
      "  Benefit 1: ____________________________",
      "  Benefit 2: ____________________________",
      "  Benefit 3: ____________________________",
      "",
      "SECTION 7 - OBJECTIONS (FAQ)",
      "  Q: ________________  A: ________________",
      "  Q: ________________  A: ________________",
      "  Q: ________________  A: ________________",
      "",
      "SECTION 8 - OFFER RECAP + CTA",
      "  What's included: ______________________",
      "  Price: Rs. ______  Guarantee: ____________",
      "  Button: \"________________________\"",
      "",
      "SECTION 9 - FINAL CTA + GUARANTEE",
      "  Button repeats + risk reversal line",
      "",
      "CHECK: one promise, one CTA, proof near decisions,",
      "everything visible on mobile.",
    ],
  },
  {
    title: "Headline & CTA Formulas",
    slug: "headline-cta-formulas",
    type: "pdf",
    description:
      "15 headline formulas and 12 CTA buttons with fill-in templates for testing.",
    sortOrder: 13,
    pdfLines: [
      "HEADLINE & CTA FORMULAS",
      "ZetaGrow Business Execution Toolkit | File 13 of 24",
      "",
      "HEADLINE FORMULAS",
      "  1. OUTCOME: \"[Result] in [time]\"",
      "  2. NUMBER: \"[N] [steps/mistakes] to [result]\"",
      "  3. QUESTION: \"Why do [audience] fail at [task]?\"",
      "  4. HOW-TO: \"How to [result] without [pain]\"",
      "  5. SECRET: \"The [result] strategy nobody talks about\"",
      "  6. NEGATIVE: \"Stop [pain] for good\"",
      "  7. AUDIENCE: \"For [specific audience] only\"",
      "  8. PROOF: \"How we helped [N] customers [result]\"",
      "  9. GUARANTEE: \"[Result] or your money back\"",
      "  10. COMPARISON: \"Why [alternative] fails you\"",
      "  11. TIME: \"[Result] in [N] minutes a day\"",
      "  12. COST: \"The real cost of [problem]\"",
      "  13. STORY: \"[Small moment] changed everything\"",
      "  14. TRUTH: \"The uncomfortable truth about [topic]\"",
      "  15. OFFER: \"Get [deliverable] for Rs. [price]\"",
      "",
      "YOUR 3 TEST HEADLINES",
      "  1. \"________________________________________\"",
      "  2. \"________________________________________\"",
      "  3. \"________________________________________\"",
      "",
      "CTA BUTTON FORMULAS",
      "  1. \"Enroll Now - Start Today\"",
      "  2. \"Get the Checklist Free\"",
      "  3. \"Book My Free Call\"",
      "  4. \"Start My 30-Day Plan\"",
      "  5. \"Get Instant Access\"",
      "  6. \"Claim the Offer\"",
      "  7. \"Send WhatsApp Message\"",
      "  8. \"Build My Landing Page\"",
      "  9. \"Download the Template\"",
      "  10. \"Join Now - Limited Spots\"",
      "  11. \"See If You Qualify\"",
      "  12. \"Get My Price\"",
      "",
      "YOUR CTA: \"________________________\"",
      "",
      "RULES",
      "  - One promise per page; headline + CTA must agree",
      "  - Test headlines first - they move conversion most",
      "  - CTA = action verb + what they get",
      "",
      "RULE: Write 3 headlines, test, keep the winner.",
    ],
  },
  {
    title: "Landing Page Checklist",
    slug: "landing-page-checklist",
    type: "pdf",
    description:
      "The pre-launch checklist: message matching, proof, objections, CTA discipline, friction, mobile, tracking.",
    sortOrder: 14,
    pdfLines: [
      "LANDING PAGE CHECKLIST",
      "ZetaGrow Business Execution Toolkit | File 14 of 24",
      "",
      "URL: ______________________________  DATE: ____________",
      "",
      "MESSAGE MATCHING",
      "  [ ] Headline matches the ad's promise",
      "  [ ] Offer on page = offer in ad",
      "  [ ] CTA text matches the ad's CTA",
      "",
      "THE ONE ACTION",
      "  [ ] One primary CTA, visible without scrolling",
      "  [ ] No competing links in the decision area",
      "  [ ] CTA repeats after proof and after FAQ",
      "",
      "PROOF",
      "  [ ] Real numbers shown",
      "  [ ] Named testimonial or review",
      "  [ ] Guarantee visible near the CTA",
      "",
      "OBJECTIONS",
      "  [ ] Top 3 objections answered in FAQ",
      "  [ ] 'Who this is not for' stated (builds trust)",
      "",
      "FRICTION REMOVAL",
      "  [ ] Minimum form fields (name + contact ideal)",
      "  [ ] No forced signup before value",
      "  [ ] Checkout: UPI + cards, one page",
      "  [ ] Loads fast on mobile data",
      "",
      "MOBILE",
      "  [ ] Single column, big tap targets",
      "  [ ] No covering popups",
      "  [ ] Tested on a real phone",
      "",
      "MEASUREMENT",
      "  [ ] Conversion event installed and verified",
      "  [ ] Source tracking (which ad brought them)",
      "",
      "RULE: The page answers 3 questions: what is this, why",
      "should I care, what do I do now.",
    ],
  },
  // ── Sales Templates (3) ─────────────────────────────────────
  {
    title: "Discovery Call Script",
    slug: "discovery-call-script",
    type: "pdf",
    description:
      "The 15-minute discovery call structure: open, situation, past attempts, costs, outcome, qualify, next step.",
    sortOrder: 15,
    pdfLines: [
      "DISCOVERY CALL SCRIPT",
      "ZetaGrow Business Execution Toolkit | File 15 of 24",
      "",
      "CALL PREP (before dialing)",
      "  Lead source: ______________________________",
      "  What they asked for: ______________________",
      "  Their likely problem: ______________________",
      "",
      "1. OPEN (2 min)",
      "  \"Thanks for your time, [name]. To make this useful,",
      "  could you tell me what you're trying to solve?\"",
      "",
      "2. SITUATION (3 min)",
      "  - \"How does [task] work for you today?\"",
      "  - \"What have you tried so far?\"",
      "  - \"What happened?\"",
      "",
      "3. PAST ATTEMPTS (3 min)",
      "  - \"What did you spend on previous attempts?\"",
      "  - \"What stopped them from working?\"",
      "",
      "4. COSTS (3 min)",
      "  - \"What does this problem cost you in time?\"",
      "  - \"In money? In stress?\"",
      "  Use their words; mirror them back.",
      "",
      "5. DESIRED OUTCOME (2 min)",
      "  - \"If this worked perfectly, what would that look like?\"",
      "  - \"By when?\"",
      "",
      "6. QUALIFY (1 min)",
      "  Problem [ ]  Budget [ ]  Authority [ ]  Timing [ ]",
      "  Score: ____________",
      "",
      "7. NEXT STEP",
      "  Qualified: \"Here is how I can help... Shall I send the",
      "  proposal today?\"",
      "  Unqualified: \"Let me share something useful anyway\"",
      "  (value first, stay in touch).",
      "",
      "RULES: 70/30 listening. No pitching in the first 10",
      "minutes. Mirror their language - the proposal will use it.",
    ],
  },
  {
    title: "Proposal Template",
    slug: "proposal-template",
    type: "pdf",
    description:
      "One-page proposal structure: problem in their words, solution, investment with anchor, guarantee, next step.",
    sortOrder: 16,
    pdfLines: [
      "PROPOSAL TEMPLATE",
      "ZetaGrow Business Execution Toolkit | File 16 of 24",
      "",
      "CLIENT: ______________________  DATE: ____________",
      "",
      "1. THE PROBLEM (their words, from discovery)",
      "  \"________________________________________\"",
      "",
      "2. THE GOAL",
      "  \"________________________________________\"",
      "  By: ____________",
      "",
      "3. THE SOLUTION (package)",
      "  Deliverable 1: __________________________",
      "  Deliverable 2: __________________________",
      "  Deliverable 3: __________________________",
      "  Timeline: ______________________________",
      "",
      "4. THE INVESTMENT",
      "  Package price: Rs. ______",
      "  Value anchor: Rs. ______",
      "  Payment terms: __________________________",
      "",
      "5. THE GUARANTEE / PROTECTION",
      "  ______________________________",
      "",
      "6. WHAT HAPPENS NEXT",
      "  1. You confirm by [date]",
      "  2. I send the agreement + payment link",
      "  3. Kickoff: [date]",
      "",
      "7. WHY US (2 lines of proof)",
      "  ______________________________",
      "",
      "SEND RULES",
      "  - Send the same day as the call",
      "  - Follow up: day 1, day 3 (value add), day 7",
      "    (case study), day 14 (decision question)",
      "",
      "RULE: One page, their words, one clear next step.",
    ],
  },
  {
    title: "Follow-up & Closing Scripts",
    slug: "follow-up-closing-scripts",
    type: "pdf",
    description:
      "Ready-to-send follow-up templates for proposals, no-shows, stalled deals, and the direct close.",
    sortOrder: 17,
    pdfLines: [
      "FOLLOW-UP & CLOSING SCRIPTS",
      "ZetaGrow Business Execution Toolkit | File 17 of 24",
      "",
      "FOLLOW-UP 1 (same day as proposal)",
      "  \"Hi [name], here is your proposal: [link]. One thing to",
      "  note: [the one differentiator]. If you have any",
      "  questions, I'm available today.\"",
      "",
      "FOLLOW-UP 2 (day 3 - add value)",
      "  \"Hi [name], thought this might help while you decide:",
      "  [one useful resource]. No pressure - just wanted you",
      "  to have it.\"",
      "",
      "FOLLOW-UP 3 (day 7 - proof)",
      "  \"Hi [name], here's a result from a similar project:",
      "  [case study / testimonial]. It took [time] to get",
      "  [result]. Happy to share the details on a quick call.\"",
      "",
      "FOLLOW-UP 4 (day 14 - decision)",
      "  \"Hi [name], I don't want to keep this open forever.",
      "  If the timing isn't right, tell me and I'll close the",
      "  file. If it is, I can start [date] - the slot is open",
      "  for 48 hours.\"",
      "",
      "REOPENING A STALLED DEAL",
      "  \"Hi [name], since we last spoke, has anything changed",
      "  with [problem]? If [problem] is still costing you",
      "  [cost], the offer still stands until [date].\"",
      "",
      "THE DIRECT CLOSE (qualified lead)",
      "  \"Shall I send the payment link? I can start today.\"",
      "  Then: pause. Let them answer.",
      "",
      "OBJECTION HANDLING",
      "  Cost: \"Compared to what it costs you to not solve",
      "  this [cost of problem], the price is [price]. The",
      "  guarantee removes the risk.\"",
      "  Think: \"What part needs more clarity - the [X] or",
      "  the [Y]? Let me address that specifically.\"",
      "",
      "RULE: Every follow-up adds value; never just 'checking",
      "in'.",
    ],
  },
  // ── SOP Templates (3) ───────────────────────────────────────
  {
    title: "SOP Template",
    slug: "sop-template",
    type: "pdf",
    description:
      "The universal SOP format: task, owner, trigger, steps, tools, done-when, and quality bar.",
    sortOrder: 18,
    pdfLines: [
      "SOP TEMPLATE",
      "ZetaGrow Business Execution Toolkit | File 18 of 24",
      "",
      "SOP TITLE: ______________________________",
      "VERSION: ____  OWNER: ____________  DATE: ____________",
      "",
      "1. WHAT (task in one line)",
      "  ________________________________________",
      "",
      "2. WHO (owner + backup)",
      "  Owner: ________________  Backup: ________________",
      "",
      "3. WHEN (trigger - what starts this)",
      "  ________________________________________",
      "",
      "4. HOW (numbered steps)",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "  4. ________________________________________",
      "  5. ________________________________________",
      "  6. ________________________________________",
      "  7. ________________________________________",
      "",
      "5. TOOLS",
      "  - ____________________  - ____________________",
      "",
      "6. DONE-WHEN (definition of complete)",
      "  ________________________________________",
      "",
      "7. QUALITY BAR (what good looks like)",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "8. FAILURE MODES (what usually breaks)",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "REVIEW CADENCE: Quarterly. Run it twice, then fix it.",
      "",
      "RULE: First version better than perfect version. Write",
      "it after doing the task once.",
    ],
  },
  {
    title: "Client Onboarding SOP",
    slug: "client-onboarding-sop",
    type: "pdf",
    description:
      "The complete onboarding sequence from payment to kickoff: welcome, intake, call, plan, first milestone.",
    sortOrder: 19,
    pdfLines: [
      "CLIENT ONBOARDING SOP",
      "ZetaGrow Business Execution Toolkit | File 19 of 24",
      "",
      "TRIGGER: Payment received or agreement signed.",
      "OWNER: Delivery lead.  TARGET: fully onboarded within",
      "48 hours.",
      "",
      "STEP 1 - WELCOME (within 1 hour of payment)",
      "  Send: welcome email with access details.",
      "  Template line: \"Welcome, [name]! Here is how",
      "  everything works: [links]. You'll hear from us",
      "  within 24 hours with next steps.\"",
      "",
      "STEP 2 - INTAKE FORM (same day)",
      "  Ask: goals, timeline, current situation, examples,",
      "  contact preferences.",
      "  Log answers in the CRM.",
      "",
      "STEP 3 - KICKOFF CALL (within 48 hours)",
      "  Agenda: goals, scope confirmation, deliverables,",
      "  timeline, communication rules, one first win.",
      "  Send call notes + action items same day.",
      "",
      "STEP 4 - PROJECT PLAN (same day as call)",
      "  Deliverables list with dates, milestones, and",
      "  revision limits.",
      "  Client approves the plan explicitly.",
      "",
      "STEP 5 - FIRST MILESTONE SCHEDULED",
      "  Date set for first deliverable: ____________",
      "",
      "DONE-WHEN: Client has access, plan approved, first",
      "milestone dated, and expectations in writing.",
      "",
      "FAILURE MODES",
      "  - No response to intake -> follow up twice, then flag",
      "  - Vague goals -> call before any work starts",
      "",
      "RULE: Onboarding sets expectations; expectations set",
      "reviews.",
    ],
  },
  {
    title: "Delivery & Quality Control SOP",
    slug: "delivery-quality-control-sop",
    type: "pdf",
    description:
      "The delivery pipeline: brief, draft, QA checklist, client review, revisions, delivery, feedback.",
    sortOrder: 20,
    pdfLines: [
      "DELIVERY & QUALITY CONTROL SOP",
      "ZetaGrow Business Execution Toolkit | File 20 of 24",
      "",
      "TRIGGER: Project kickoff approved.",
      "OWNER: Project lead.",
      "",
      "STEP 1 - BRIEF CONFIRMATION",
      "  Restate scope, deliverables, timeline, revision",
      "  limit. Get written approval.",
      "",
      "STEP 2 - DRAFT",
      "  Build the deliverable per the plan.",
      "  Internal deadline: 1 day before client deadline.",
      "",
      "STEP 3 - INTERNAL QA (the checklist)",
      "  [ ] Facts and numbers verified",
      "  [ ] No broken links; files open correctly",
      "  [ ] Spelling and grammar clean",
      "  [ ] Mobile view checked",
      "  [ ] Branding consistent",
      "  [ ] Second pair of eyes for client-facing work",
      "",
      "STEP 4 - CLIENT REVIEW",
      "  Send with a summary: what was done, what to look at,",
      "  deadline for feedback (e.g., 3 days).",
      "",
      "STEP 5 - REVISIONS",
      "  Track against the agreed revision limit.",
      "  Changes outside scope -> polite new quote.",
      "  Change log: what changed, when, by whom.",
      "",
      "STEP 6 - DELIVERY",
      "  Deliver early whenever possible.",
      "  Include: final files + one-paragraph results summary.",
      "",
      "STEP 7 - FEEDBACK REQUEST",
      "  Ask for a review the day after delivery.",
      "  Template: \"We'd love your honest feedback -",
      "  [review link]. It helps us serve you better.\"",
      "",
      "DONE-WHEN: Deliverable sent, QA signed off, feedback",
      "requested.",
      "",
      "RULE: Early delivery is the cheapest marketing you can",
      "buy.",
    ],
  },
  // ── Business Calculators (3) ────────────────────────────────
  {
    title: "Pricing Calculator",
    slug: "pricing-calculator",
    type: "pdf",
    description:
      "Value-based pricing worksheet: outcome value, cost basis, anchor, tier pricing, and margin check.",
    sortOrder: 21,
    pdfLines: [
      "PRICING CALCULATOR",
      "ZetaGrow Business Execution Toolkit | File 21 of 24",
      "",
      "STEP 1 - COST BASIS",
      "  Cost to deliver (time + tools): Rs. ______",
      "  Monthly fixed costs: Rs. ______",
      "",
      "STEP 2 - OUTCOME VALUE",
      "  What the customer gains, in money: Rs. ______ /",
      "  year",
      "  What the problem costs them: Rs. ______ / year",
      "",
      "STEP 3 - VALUE-BASED PRICE",
      "  Price range: Rs. ______ to Rs. ______",
      "  (10-20% of the outcome value is a common range)",
      "",
      "STEP 4 - ANCHOR",
      "  Reference value (sum of components): Rs. ______",
      "  Your price: Rs. ______",
      "",
      "STEP 5 - TIER PRICING",
      "  Basic: Rs. ______  Standard: Rs. ______",
      "  Premium: Rs. ______",
      "  (Most buyers pick the middle - price it deliberately)",
      "",
      "STEP 6 - MARGIN CHECK",
      "  Price - delivery cost = margin: Rs. ______",
      "  Margin %: ______%  Healthy if above 60%",
      "",
      "STEP 7 - PRICE INCREASE PLAN",
      "  Current price: Rs. ______",
      "  Next price: Rs. ______  Date: ____________",
      "  (Raise every 3-6 months; deliver more value each time)",
      "",
      "RULE: Price by outcome value, not effort. Test price",
      "changes - raise and measure.",
    ],
  },
  {
    title: "Break-even Calculator",
    slug: "break-even-calculator",
    type: "pdf",
    description:
      "Compute break-even CPA and ROAS for any product, plus the margin math every campaign needs.",
    sortOrder: 22,
    pdfLines: [
      "BREAK-EVEN CALCULATOR",
      "ZetaGrow Business Execution Toolkit | File 22 of 24",
      "",
      "STEP 1 - UNIT ECONOMICS",
      "  Price: Rs. ______",
      "  Variable costs (delivery, fees, tools): Rs. ______",
      "  Margin per sale = price - variable costs: Rs. ______",
      "",
      "STEP 2 - BREAK-EVEN CPA",
      "  Break-even CPA = margin per sale",
      "  = Rs. ______",
      "  (Below this CPA, every sale loses money)",
      "",
      "STEP 3 - BREAK-EVEN ROAS",
      "  Break-even ROAS = price / margin",
      "  = ______x",
      "  (Below this ROAS, the campaign loses money)",
      "",
      "STEP 4 - FIXED COSTS",
      "  Monthly fixed costs: Rs. ______",
      "  Sales needed to cover fixed costs = fixed costs /",
      "  margin = ______ sales / month",
      "",
      "STEP 5 - FULL CAC CHECK",
      "  Total marketing + sales costs / customers: Rs. ______",
      "  Is full CAC below break-even CPA? [ ] Yes  [ ] No",
      "",
      "STEP 6 - LTV CHECK",
      "  LTV: Rs. ______   LTV : CAC = ______x",
      "  (Healthy target: 3x or higher)",
      "",
      "EXAMPLE",
      "  Price Rs. 999, variable Rs. 99 -> margin Rs. 900.",
      "  Break-even CPA = Rs. 900. Break-even ROAS = 1.1x.",
      "  Any campaign below 1.1x ROAS buys customers at a",
      "  loss.",
      "",
      "RULE: Know your break-even before you spend a rupee.",
    ],
  },
  {
    title: "LTV/CAC Calculator",
    slug: "ltv-cac-calculator",
    type: "pdf",
    description:
      "Customer lifetime value and acquisition cost math: retention, repeat rate, AOV, and the 3x rule.",
    sortOrder: 23,
    pdfLines: [
      "LTV / CAC CALCULATOR",
      "ZetaGrow Business Execution Toolkit | File 23 of 24",
      "",
      "PART A - CUSTOMER ACQUISITION COST (CAC)",
      "  Total marketing + sales spend (month): Rs. ______",
      "  New customers (month): ______",
      "  CAC = spend / customers = Rs. ______",
      "",
      "PART B - AVERAGE ORDER VALUE (AOV)",
      "  Revenue (month): Rs. ______",
      "  Orders (month): ______",
      "  AOV = revenue / orders = Rs. ______",
      "",
      "PART C - REPEAT RATE",
      "  Customers who bought again: ______",
      "  Repeat rate = repeat customers / total: ______%",
      "",
      "PART D - CUSTOMER LIFETIME (months)",
      "  Churn rate (customers lost / month): ______%",
      "  Lifetime = 1 / churn rate = ______ months",
      "",
      "PART E - LIFETIME VALUE (LTV)",
      "  Simple: LTV = AOV x repeat purchases = Rs. ______",
      "  Full: LTV = AOV x purchase frequency x lifetime",
      "  = Rs. ______",
      "",
      "PART F - THE 3X RULE",
      "  LTV : CAC = ______x",
      "  < 1x  : you lose money on every customer",
      "  1-3x  : growing - fix retention before scaling",
      "  3x+   : healthy - scaling ads is justified",
      "",
      "LEVERS TO PULL",
      "  - Raise LTV: increase AOV (upsells), increase",
      "    frequency (retention offers), reduce churn",
      "    (onboarding)",
      "  - Lower CAC: better targeting, better landing pages,",
      "    referrals, retargeting",
      "",
      "RULE: Marketing decisions should live on this page.",
    ],
  },
  // ── 30-Day Plan (1) ─────────────────────────────────────────
  {
    title: "30-Day Implementation Plan",
    slug: "30-day-implementation-plan",
    type: "pdf",
    description:
      "The complete day-by-day roadmap: Week 1 research + offer, Week 2 website + content, Week 3 marketing + leads, Week 4 automation + analytics.",
    sortOrder: 24,
    pdfLines: [
      "30-DAY IMPLEMENTATION PLAN",
      "ZetaGrow Business Execution Toolkit | File 24 of 24",
      "",
      "WEEK 1 - RESEARCH + OFFER",
      "  Day 1:  Niche decision (skill x demand x reach)",
      "  Day 2:  Customer research (3 interviews / 20 reviews)",
      "  Day 3:  Competitor map (offer, price, strengths, gaps)",
      "  Day 4:  Market gap statement - the one gap you own",
      "  Day 5:  Offer Builder complete",
      "  Day 6:  Break-even CPA + LTV:CAC targets set",
      "  Day 7:  One-paragraph offer statement, feedback, iterate",
      "",
      "WEEK 2 - WEBSITE + CONTENT",
      "  Day 8:  Landing page structure (headline, proof, FAQ)",
      "  Day 9:  Build the landing page",
      "  Day 10: Write 3 headline + CTA test versions",
      "  Day 11: Content pillars + 10 ideas per pillar",
      "  Day 12: Batch content session (week 3 content)",
      "  Day 13: Repurpose one core piece into 6 pieces",
      "  Day 14: KPI thresholds + reporting SOP live",
      "",
      "WEEK 3 - MARKETING + LEADS",
      "  Day 15: Lead magnet + capture form live",
      "  Day 16: Meta campaign plan (objective, budget, matrix)",
      "  Day 17: Creative set (3 hooks x 3 formats)",
      "  Day 18: Launch campaign with tracking verified",
      "  Day 19: Follow-up sequence built (3-5 messages)",
      "  Day 20: Retargeting ad set live",
      "  Day 21: First diagnosis - change ONE thing",
      "",
      "WEEK 4 - AUTOMATION + ANALYTICS + OPTIMIZATION",
      "  Day 22: CRM/sheet organized - every lead has a status",
      "  Day 23: AI workflow #1 automated (lead replies)",
      "  Day 24: Onboarding sequence delivered",
      "  Day 25: Report #1 (CTR, CPL, CPA, ROAS vs targets)",
      "  Day 26: Search terms / negatives / exclusions review",
      "  Day 27: One new test with a written decision rule",
      "  Day 28: Review + referral asks automated",
      "  Day 29: SOPs for the 3 most repeated tasks",
      "  Day 30: Month review - wins, losses, next month's focus",
      "",
      "RULES",
      "  1. 2-3 focused hours daily beats 12 scattered ones",
      "  2. Miss a day? Compress the next two - never skip",
      "  3. Ship imperfect - the first version wins",
      "  4. Every decision gets a review date",
      "  5. Measure everything you can",
      "",
      "DAY 1 STARTS TODAY.",
    ],
  },
];