/**
 * Growth Professional (₹4,000) — 28-file Growth Bundle definitions.
 * Each resource is generated as a PDF and stored in Convex.
 */

export interface GrowthResourceDef {
  title: string;
  slug: string;
  type: "pdf";
  description: string;
  sortOrder: number;
  pdfLines: string[];
}

export const GROWTH_RESOURCES: GrowthResourceDef[] = [
  // ── Paid Ads (9) ──────────────────────────────────────────────
  {
    title: "Meta Ads Campaign Planning Template",
    slug: "meta-ads-campaign-planning-template",
    type: "pdf",
    description:
      "Plan any Meta campaign before you open Ads Manager: objective, budget, audience, placements, creative and success metrics.",
    sortOrder: 1,
    pdfLines: [
      "META ADS CAMPAIGN PLANNING TEMPLATE",
      "ZetaGrow Growth Bundle | File 1 of 28",
      "",
      "1. BUSINESS GOAL",
      "  What business result does this campaign need to create?",
      "  (Leads / Sales / Engaged audience / App installs)",
      "  Goal: ______________________________",
      "",
      "2. CAMPAIGN OBJECTIVE (pick ONE)",
      "  [ ] Sales    [ ] Leads    [ ] Traffic",
      "  [ ] Engagement    [ ] Awareness",
      "",
      "3. CONVERSION LOCATION",
      "  [ ] Website (Pixel)  [ ] WhatsApp / Messenger",
      "  [ ] Instant form (Lead Ads)",
      "",
      "4. AUDIENCE (Module 3)",
      "  Type:  [ ] Broad  [ ] Interest  [ ] Custom  [ ] Lookalike",
      "  Ages: ____ to ____   Gender: [ ] All  [ ] M  [ ] F",
      "  Location: ______________________________",
      "  Interests / source audience: ________________",
      "  Exclusions: ______________________________",
      "",
      "5. BUDGET & SCHEDULE",
      "  Daily budget: Rs. ______   Total budget: Rs. ______",
      "  Duration: ______ days   Start: ____________",
      "",
      "6. CREATIVE (one row per ad)",
      "  Ad 1 | Format: ______ | Hook: ________________",
      "  Ad 2 | Format: ______ | Hook: ________________",
      "  Ad 3 | Format: ______ | Hook: ________________",
      "",
      "7. LANDING PAGE / NEXT STEP",
      "  URL or flow: ______________________________",
      "  Headline (must match ad): __________________",
      "  One CTA: __________________________________",
      "",
      "8. SUCCESS METRICS & THRESHOLDS",
      "  CTR target: ____   CPL/CPA target: Rs. ______",
      "  ROAS target: ____   Review date: ____________",
      "",
      "RULE: One campaign = one objective. Never mix.",
    ],
  },
  {
    title: "Google Ads Campaign Planning Template",
    slug: "google-ads-campaign-planning-template",
    type: "pdf",
    description:
      "Plan a Google Search campaign: keywords, match types, ad groups, negative keywords, landing page and measurement.",
    sortOrder: 2,
    pdfLines: [
      "GOOGLE ADS CAMPAIGN PLANNING TEMPLATE",
      "ZetaGrow Growth Bundle | File 2 of 28",
      "",
      "1. CAMPAIGN TYPE",
      "  [ ] Search (start here)  [ ] Display  [ ] Shopping  [ ] Video",
      "",
      "2. CAMPAIGN NAME (naming convention)",
      "  E.g. GA-Search-DigitalMarketingCourse-Exact-2026",
      "  Name: ________________________________",
      "",
      "3. KEYWORD LIST (5-15 per ad group)",
      "  Group 1 theme: ______________________",
      "  Keywords (exact/phrase):",
      "  - ____________________  - ____________________",
      "  - ____________________  - ____________________",
      "  Group 2 theme: ______________________",
      "  Keywords:",
      "  - ____________________  - ____________________",
      "  - ____________________  - ____________________",
      "",
      "4. NEGATIVE KEYWORDS",
      "  - free  - job  - salary  - cheap  - tutorial (if selling)",
      "  Add yours: ______________________________",
      "",
      "5. ADS (2 per ad group)",
      "  Headline 1 (keyword + offer): __________________",
      "  Headline 2 (differentiator): ___________________",
      "  Description (benefit + CTA): __________________",
      "",
      "6. LANDING PAGE (message matching)",
      "  URL: ________________________________",
      "  Same keyword in H1?  [ ] Yes  [ ] No",
      "  One CTA only?        [ ] Yes  [ ] No",
      "",
      "7. BIDDING",
      "  [ ] Maximize conversions (needs history)",
      "  [ ] Maximize clicks with max CPC of Rs. ______",
      "",
      "8. MEASUREMENT",
      "  Conversion action set up?  [ ] Yes  [ ] No",
      "  Target CPA: Rs. ______",
      "",
      "RULE: Ad group = one theme = 5-15 keywords.",
    ],
  },
  {
    title: "Audience Research Worksheet",
    slug: "audience-research-worksheet",
    type: "pdf",
    description:
      "Define your cold, warm and hot audiences, estimate sizes, and write the one-line message for each temperature.",
    sortOrder: 3,
    pdfLines: [
      "AUDIENCE RESEARCH WORKSHEET",
      "ZetaGrow Growth Bundle | File 3 of 28",
      "",
      "COLD AUDIENCE (never heard of you)",
      "  Description: ______________________________",
      "  Targeting: [ ] Broad  [ ] Interests: ____________",
      "  Age range: ____ to ____   Location: ____________",
      "  Estimated size (Ads Manager): ____________",
      "  One-line message (problem + solution):",
      "  \"________________________________________\"",
      "",
      "WARM AUDIENCE (saw content / engaged)",
      "  Sources: [ ] Video viewers 50%  [ ] Engaged users",
      "           [ ] Website visitors  [ ] Lead form",
      "  Lookback window: ______ days",
      "  One-line message (proof + credibility):",
      "  \"________________________________________\"",
      "",
      "HOT AUDIENCE (about to buy)",
      "  Sources: [ ] Cart abandoners  [ ] Product viewers",
      "           [ ] WhatsApp replies  [ ] Customer list",
      "  One-line message (offer + urgency):",
      "  \"________________________________________\"",
      "",
      "OVERLAP CHECK",
      "  Audiences duplicated across ad sets?  [ ] Yes  [ ] No",
      "  Purchasers excluded?                   [ ] Yes  [ ] No",
      "",
      "RULE: Cold gets education, warm gets proof, hot gets the offer.",
    ],
  },
  {
    title: "Ad-Copy Templates",
    slug: "ad-copy-templates",
    type: "pdf",
    description:
      "Ready-to-fill copy templates: primary text, headlines, descriptions, CTA prompts and 10 proven formulas.",
    sortOrder: 4,
    pdfLines: [
      "AD-COPY TEMPLATES",
      "ZetaGrow Growth Bundle | File 4 of 28",
      "",
      "STRUCTURE OF PRIMARY TEXT",
      "  Line 1 - Hook: ________________________________",
      "  Line 2 - Problem: ____________________________",
      "  Line 3 - Solution: ___________________________",
      "  Line 4 - Proof: ______________________________",
      "  Line 5 - Offer: ______________________________",
      "  Line 6 - CTA: ________________________________",
      "",
      "10 COPY FORMULAS",
      "  1. PROBLEM-AGITATE-SOLVE: \"Your ads get clicks but",
      "     no sales. Here is why - and the fix.\"",
      "  2. BEFORE-AFTER-BRIDGE: \"Before: wasted Rs. 20,000.",
      "     After: a system that works.\"",
      "  3. CURIOUS QUESTION: \"Why do 90% of local ads fail?\"",
      "  4. NUMBER LIST: \"5 landing page mistakes that cost",
      "     you customers.\"",
      "  5. MYTH BUST: \"Big reach is a lie. Here is the truth.\"",
      "  6. STORY OPEN: \"I almost shut the store. Then I",
      "     changed one thing.\"",
      "  7. OBJECTION FIRST: \"Too expensive? Read this first.\"",
      "  8. TESTIMONIAL: \"\"This course paid for itself in a",
      "     week.\" - real student\"",
      "  9. URGENCY: \"First 50 enrollments at this price.\"",
      "  10. GUARANTEE: \"Try it for 7 days or get a refund.\"",
      "",
      "HEADLINES",
      "  [Keyword] + [Offer]: \"Digital Marketing Course - Rs. 4,000\"",
      "  [Differentiator]: \"Lifetime Access + 28 Templates\"",
      "",
      "CTA PROMPTS",
      "  Buy Now / Learn More / Send WhatsApp Message",
      "  Book a Free Call / Get Started / Enroll Today",
      "",
      "RULE: One CTA per ad. Write 3 versions, test the best.",
    ],
  },
  {
    title: "Creative Brief Template",
    slug: "creative-brief-template",
    type: "pdf",
    description:
      "One-page brief for every creative: goal, audience, hook, message, proof, format, visual and success criteria.",
    sortOrder: 5,
    pdfLines: [
      "CREATIVE BRIEF TEMPLATE",
      "ZetaGrow Growth Bundle | File 5 of 28",
      "",
      "CAMPAIGN / AD SET: ______________________________",
      "CREATIVE NAME: ______________________________",
      "",
      "1. GOAL",
      "  What should this ad achieve? __________________",
      "",
      "2. AUDIENCE",
      "  Who exactly sees this? (temperature + description)",
      "  ________________________________________",
      "",
      "3. HOOK (first 3 seconds / first line)",
      "  \"________________________________________\"",
      "",
      "4. CORE MESSAGE",
      "  One sentence the viewer must remember:",
      "  \"________________________________________\"",
      "",
      "5. PROOF",
      "  [ ] Number   [ ] Testimonial   [ ] Demo   [ ] Before/After",
      "  Detail: __________________________________",
      "",
      "6. OFFER & CTA",
      "  Offer: __________________________________",
      "  CTA button: ______________________________",
      "",
      "7. FORMAT & VISUAL",
      "  [ ] Reel video  [ ] Static  [ ] Carousel  [ ] UGC",
      "  First frame describes: ______________________",
      "  Text overlay present: [ ] Yes  [ ] No",
      "",
      "8. SUCCESS CRITERIA",
      "  CTR above ____%  /  completion above ____%",
      "  Review after: ______ days  /  budget: Rs. ______",
      "",
      "RULE: One brief per creative. No brief, no ad.",
    ],
  },
  {
    title: "Campaign Naming Convention",
    slug: "campaign-naming-convention",
    type: "pdf",
    description:
      "A standard naming system so every campaign, ad set and ad is readable at a glance in Ads Manager.",
    sortOrder: 6,
    pdfLines: [
      "CAMPAIGN NAMING CONVENTION",
      "ZetaGrow Growth Bundle | File 6 of 28",
      "",
      "FORMAT",
      "  Platform-Objective-Target-TrafficType-Date",
      "",
      "EXAMPLES",
      "  FB-Sales-India-Cold-2026-08",
      "  FB-Leads-Jaipur-Warm-2026-08",
      "  IG-Traffic-Lookalike-Cold-2026-08",
      "  GA-Search-Course-Exact-2026-08",
      "",
      "CAMPAIGN LEVEL",
      "  Platform: FB / IG / GA / YT",
      "  Objective: Sales / Leads / Traffic / Search",
      "  Target: Country, City, or Product name",
      "",
      "AD SET LEVEL (add to campaign name)",
      "  Temperature: Cold / Warm / Hot / Retarget",
      "  Audience name: Broad / Int-DigitalMarketing /",
      "    Lookalike-2% / Cart-Abandoners",
      "",
      "AD LEVEL (add to ad set name)",
      "  Creative: HookX_Format (e.g. Claim1_Reel, Q2_Carousel)",
      "  Offer: OfferA / OfferB",
      "",
      "EXAMPLE FULL NAME",
      "  FB-Sales-India-Cold-Broad-Claim1_Reel-OfferA",
      "",
      "BENEFITS",
      "  - Any teammate can read the account in 5 seconds",
      "  - Performance reviews sort by name",
      "  - No more \"campaign 2\" mysteries",
      "",
      "RULE: Name it like a file path - every segment means something.",
    ],
  },
  {
    title: "Budget Calculator",
    slug: "budget-calculator",
    type: "pdf",
    description:
      "Work out what budget your goal needs: reverse from target sales to clicks, cost per click and test duration.",
    sortOrder: 7,
    pdfLines: [
      "BUDGET CALCULATOR",
      "ZetaGrow Growth Bundle | File 7 of 28",
      "",
      "STEP 1 - REVERSE FROM YOUR GOAL",
      "  Target sales/leads: ____________ (A)",
      "  Expected landing page conversion: ____% (B)",
      "  Clicks needed = A / (B / 100): ____________ (C)",
      "",
      "STEP 2 - COST OF CLICKS",
      "  Expected cost per click: Rs. ______ (D)",
      "  Click budget = C x D: Rs. ____________ (E)",
      "",
      "STEP 3 - CREATIVE TEST BUDGET",
      "  Minimum to learn (C x 3 minimum): Rs. ____________",
      "",
      "STEP 4 - FULL CAMPAIGN BUDGET",
      "  Click budget (E): Rs. ____________",
      "  Test reserve (+50%): Rs. ____________",
      "  Retargeting share (20-30%): Rs. ____________",
      "  TOTAL: Rs. ____________",
      "",
      "SANITY CHECKS",
      "  [ ] Budget covers at least 50 clicks per ad set",
      "  [ ] Test period is 3-5 days minimum",
      "  [ ] You can afford to lose the test budget",
      "",
      "EXAMPLE",
      "  10 sales target, 2% conversion = 500 clicks.",
      "  CPC Rs. 60 = Rs. 30,000 + 50% reserve = Rs. 45,000.",
      "  If that is too much: reduce target, not test quality.",
      "",
      "RULE: Budget follows the goal, never the other way.",
    ],
  },
  {
    title: "Campaign Testing Worksheet",
    slug: "campaign-testing-worksheet",
    type: "pdf",
    description:
      "Track every test: hypothesis, one variable changed, budget, duration, result, and the decision taken.",
    sortOrder: 8,
    pdfLines: [
      "CAMPAIGN TESTING WORKSHEET",
      "ZetaGrow Growth Bundle | File 8 of 28",
      "",
      "TEST 1",
      "  Date started: ____________   Ended: ____________",
      "  Hypothesis: __________________________________",
      "  Variable changed (only ONE): __________________",
      "  Control: ____________________________________",
      "  Budget: Rs. ______   Duration: ______ days",
      "  Result (CTR/CPL/CPA/ROAS): __________________",
      "  Decision: [ ] Scale  [ ] Kill  [ ] Iterate",
      "  Learning (one line): __________________________",
      "",
      "TEST 2",
      "  Date started: ____________   Ended: ____________",
      "  Hypothesis: __________________________________",
      "  Variable changed (only ONE): __________________",
      "  Control: ____________________________________",
      "  Budget: Rs. ______   Duration: ______ days",
      "  Result (CTR/CPL/CPA/ROAS): __________________",
      "  Decision: [ ] Scale  [ ] Kill  [ ] Iterate",
      "  Learning (one line): __________________________",
      "",
      "TEST 3",
      "  Date started: ____________   Ended: ____________",
      "  Hypothesis: __________________________________",
      "  Variable changed (only ONE): __________________",
      "  Control: ____________________________________",
      "  Budget: Rs. ______   Duration: ______ days",
      "  Result (CTR/CPL/CPA/ROAS): __________________",
      "  Decision: [ ] Scale  [ ] Kill  [ ] Iterate",
      "  Learning (one line): __________________________",
      "",
      "RULE: One variable per test. 3-5 days minimum. Record everything.",
    ],
  },
  {
    title: "Optimization Checklist",
    slug: "optimization-checklist",
    type: "pdf",
    description:
      "The weekly diagnostic checklist: creative, audience, landing page, bidding, and scaling decisions in order.",
    sortOrder: 9,
    pdfLines: [
      "OPTIMIZATION CHECKLIST",
      "ZetaGrow Growth Bundle | File 9 of 28",
      "",
      "WEEKLY REVIEW - CAMPAIGN: ______________________",
      "  Date: ____________",
      "",
      "1. MESSAGE LEVEL",
      "  [ ] CTR below target? -> creative/message problem.",
      "      New hook or first frame needed, not new audience.",
      "  [ ] Hook rewritten this week? (test one new hook)",
      "",
      "2. CONVERSION LEVEL",
      "  [ ] Clicks fine but no conversions? -> landing page",
      "      or offer problem. Check page speed, headline",
      "      match, CTA visibility, checkout friction.",
      "  [ ] Follow-up flow working? (speed of first reply)",
      "",
      "3. COST LEVEL",
      "  [ ] CPM high? -> creative fatigue or audience overlap.",
      "  [ ] CPC high but CPM fine? -> relevance/bid issue.",
      "  [ ] CPA high? -> conversion rate is the leak.",
      "",
      "4. AUDIENCE LEVEL",
      "  [ ] Frequency above 3-4 with falling CTR?",
      "      -> refresh creative or widen audience.",
      "  [ ] Purchasers excluded?  [ ] Overlap checked?",
      "",
      "5. SCALING",
      "  [ ] Scale only the top 1-2 performers, +20-30% at a",
      "      time, never overnight doubles.",
      "  [ ] New test launched? (one variable only)",
      "",
      "6. LEARNING LOG",
      "  This week's biggest learning:",
      "  \"________________________________________\"",
      "",
      "RULE: Diagnose first. Change one thing. Measure 3-5 days.",
    ],
  },
  // ── SEO (4) ──────────────────────────────────────────────────
  {
    title: "Keyword Research Worksheet",
    slug: "keyword-research-worksheet",
    type: "pdf",
    description:
      "Capture head terms and long-tail keywords with intent classification, volume estimates and difficulty notes.",
    sortOrder: 10,
    pdfLines: [
      "KEYWORD RESEARCH WORKSHEET",
      "ZetaGrow Growth Bundle | File 10 of 28",
      "",
      "PILLAR TOPIC: ______________________________",
      "",
      "KEYWORD TABLE",
      "  | Keyword | Intent (I/C/T) | Volume est. | Difficulty | Priority |",
      "  |---------|---------------|-------------|------------|----------|",
      "  |         |               |             |            |          |",
      "  |         |               |             |            |          |",
      "  |         |               |             |            |          |",
      "  |         |               |             |            |          |",
      "  |         |               |             |            |          |",
      "",
      "INTENT KEY",
      "  I = Informational (blog content)",
      "  C = Commercial (comparison content + ads)",
      "  T = Transactional (product pages + ads)",
      "",
      "LONG-TAIL GOLDMINE (specific, winnable)",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "  4. ________________________________________",
      "  5. ________________________________________",
      "",
      "SOURCES USED",
      "  [ ] Google autocomplete  [ ] People Also Ask",
      "  [ ] Competitor pages     [ ] Search Console data",
      "",
      "TOP 3 PRIORITY KEYWORDS FOR THIS MONTH",
      "  1. ________________  (content type: ________)",
      "  2. ________________  (content type: ________)",
      "  3. ________________  (content type: ________)",
      "",
      "RULE: Match content type to intent. Long-tail first.",
    ],
  },
  {
    title: "SEO Content Planner",
    slug: "seo-content-planner",
    type: "pdf",
    description:
      "Plan a content cluster: pillar page, supporting articles, internal links, target keywords and publish dates.",
    sortOrder: 11,
    pdfLines: [
      "SEO CONTENT PLANNER",
      "ZetaGrow Growth Bundle | File 11 of 28",
      "",
      "PILLAR PAGE",
      "  Topic: __________________________________",
      "  Target keyword: ________________________",
      "  URL: __________________________________",
      "  Status: [ ] Draft  [ ] Published  [ ] Needs update",
      "",
      "SUPPORTING ARTICLES (5-8)",
      "  1. Title: ________________________",
      "     Keyword: ________________ | Links to pillar: [ ]",
      "     Date: ____________",
      "  2. Title: ________________________",
      "     Keyword: ________________ | Links to pillar: [ ]",
      "     Date: ____________",
      "  3. Title: ________________________",
      "     Keyword: ________________ | Links to pillar: [ ]",
      "     Date: ____________",
      "  4. Title: ________________________",
      "     Keyword: ________________ | Links to pillar: [ ]",
      "     Date: ____________",
      "  5. Title: ________________________",
      "     Keyword: ________________ | Links to pillar: [ ]",
      "     Date: ____________",
      "",
      "INTERNAL LINK RULES",
      "  - Each article links UP to the pillar page",
      "  - Pillar links DOWN to each article",
      "  - 2+ internal links per article minimum",
      "",
      "ON-PAGE REMINDER",
      "  [ ] Title tag (keyword first, under 60 chars)",
      "  [ ] Meta description (155 chars, benefit + CTA)",
      "  [ ] One H1 (keyword), logical H2/H3",
      "  [ ] Answer fully in the first paragraph",
      "  [ ] Image alt text with keyword variation",
      "",
      "RULE: Own the topic, not just the keyword.",
    ],
  },
  {
    title: "On-Page SEO Checklist",
    slug: "on-page-seo-checklist",
    type: "pdf",
    description:
      "The complete per-page checklist: titles, meta, headings, content, images, internal links, and technical basics.",
    sortOrder: 12,
    pdfLines: [
      "ON-PAGE SEO CHECKLIST",
      "ZetaGrow Growth Bundle | File 12 of 28",
      "",
      "URL: ______________________________   DATE: ____________",
      "",
      "TITLE TAG",
      "  [ ] Primary keyword first",
      "  [ ] Under 60 characters",
      "  [ ] Reason to click (benefit/curiosity)",
      "  Current: ________________________________",
      "",
      "META DESCRIPTION",
      "  [ ] Around 155 characters",
      "  [ ] Benefit + CTA included",
      "  Current: ________________________________",
      "",
      "HEADINGS",
      "  [ ] Exactly one H1 containing the keyword",
      "  [ ] Logical H2/H3 hierarchy",
      "  [ ] Headings describe sections, not decorate",
      "",
      "CONTENT",
      "  [ ] Question answered in first paragraph",
      "  [ ] Natural keyword variations used",
      "  [ ] No thin content (adds real value)",
      "",
      "IMAGES",
      "  [ ] Descriptive file names",
      "  [ ] Alt text with keyword variation",
      "  [ ] Compressed / web-friendly size",
      "",
      "INTERNAL LINKS",
      "  [ ] 2+ internal links to related pages",
      "  [ ] Links use descriptive anchor text",
      "",
      "TECHNICAL BASICS",
      "  [ ] Mobile friendly",
      "  [ ] HTTPS",
      "  [ ] Clean URL structure",
      "  [ ] Page loads fast (test on mobile data)",
      "",
      "RULE: Fix the title, meta, and first paragraph first -",
      "they earn 80% of the click.",
    ],
  },
  {
    title: "Content Cluster Template",
    slug: "content-cluster-template",
    type: "pdf",
    description:
      "Map a full topic cluster: pillar topic, sub-topics, articles, keywords, and the internal linking structure.",
    sortOrder: 13,
    pdfLines: [
      "CONTENT CLUSTER TEMPLATE",
      "ZetaGrow Growth Bundle | File 13 of 28",
      "",
      "PILLAR TOPIC: ______________________________",
      "  Pillar URL: ________________________________",
      "  Pillar keyword: __________________________",
      "",
      "SUB-TOPIC 1: ______________________________",
      "  Article: ________________ | Keyword: ______________",
      "  Article: ________________ | Keyword: ______________",
      "  Article: ________________ | Keyword: ______________",
      "",
      "SUB-TOPIC 2: ______________________________",
      "  Article: ________________ | Keyword: ______________",
      "  Article: ________________ | Keyword: ______________",
      "",
      "SUB-TOPIC 3: ______________________________",
      "  Article: ________________ | Keyword: ______________",
      "  Article: ________________ | Keyword: ______________",
      "",
      "SUB-TOPIC 4: ______________________________",
      "  Article: ________________ | Keyword: ______________",
      "",
      "LINKING MAP (draw arrows)",
      "  Pillar  <--  Article A1  Article A2  Article A3",
      "  Pillar  <--  Article B1  Article B2",
      "  Pillar  <--  Article C1  Article C2",
      "  (every article links UP to the pillar)",
      "",
      "PUBLISH ORDER (long-tail first)",
      "  1. ____________  4. ____________",
      "  2. ____________  5. ____________",
      "  3. ____________  6. ____________",
      "",
      "RULE: One cluster per month. Depth beats breadth.",
    ],
  },
  // ── Marketing (5) ────────────────────────────────────────────
  {
    title: "Customer Persona Template",
    slug: "customer-persona-template",
    type: "pdf",
    description:
      "Build the detailed profile of your target customer: demographics, goals, pains, objections, and where they hang out.",
    sortOrder: 14,
    pdfLines: [
      "CUSTOMER PERSONA TEMPLATE",
      "ZetaGrow Growth Bundle | File 14 of 28",
      "",
      "PERSONA NAME: ______________________________",
      "  (Give them a name: e.g. 'Small Shop Rohan')",
      "",
      "DEMOGRAPHICS",
      "  Age: ____________  Gender: ____________",
      "  Location: ______________________________",
      "  Job / business: ________________________",
      "  Income level: __________________________",
      "",
      "GOALS & ASPIRATIONS",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "PAINS & FRUSTRATIONS",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "OBJECTIONS (what stops them buying)",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "INFORMATION SOURCES",
      "  [ ] Instagram  [ ] YouTube  [ ] WhatsApp groups",
      "  [ ] Google search  [ ] Friends/family  [ ] LinkedIn",
      "",
      "THEIR 3 BIG QUESTIONS BEFORE BUYING",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "ONE-LINE SUMMARY",
      "  \"________ is a ________ who wants ________",
      "  but struggles with ________.\"",
      "",
      "RULE: One persona per campaign. Specificity writes better ads.",
    ],
  },
  {
    title: "Funnel Planner",
    slug: "funnel-planner",
    type: "pdf",
    description:
      "Design your complete funnel: traffic, landing page, lead/purchase, follow-up, retargeting, repeat and referral.",
    sortOrder: 15,
    pdfLines: [
      "FUNNEL PLANNER",
      "ZetaGrow Growth Bundle | File 15 of 28",
      "",
      "STAGE 1 - TRAFFIC",
      "  Sources: [ ] Meta ads  [ ] Google ads  [ ] Organic",
      "  Budget: Rs. ______  /  Content cadence: ________",
      "",
      "STAGE 2 - LANDING PAGE",
      "  URL: ________________________________",
      "  Headline: ____________________________",
      "  One CTA: ____________________________",
      "  Proof shown: ________________________",
      "",
      "STAGE 3 - LEAD / PURCHASE",
      "  Mechanism: [ ] Form  [ ] WhatsApp  [ ] Checkout",
      "  Fields (fewer = better): ____________________",
      "",
      "STAGE 4 - FOLLOW-UP",
      "  Speed target: within ______ minutes",
      "  Sequence: ____________________________",
      "  Templates ready? [ ] Yes  [ ] No",
      "",
      "STAGE 5 - RETARGETING",
      "  Audience: ____________________________",
      "  Ad angle: [ ] Proof  [ ] Objection  [ ] Urgency",
      "  Budget share (20-30%): Rs. ______",
      "",
      "STAGE 6 - REPEAT / REFERRAL",
      "  Offer: ______________________________",
      "  Referral reward: ____________________",
      "  Review request: [ ] Yes  [ ] No",
      "",
      "BIGGEST LEAK TODAY (fix first)",
      "  ________________________________________",
      "",
      "RULE: Fix the biggest leak before adding more traffic.",
    ],
  },
  {
    title: "Offer Worksheet",
    slug: "offer-worksheet",
    type: "pdf",
    description:
      "Craft a complete offer: product, price, bonuses, guarantee, urgency, and the message that sells it.",
    sortOrder: 16,
    pdfLines: [
      "OFFER WORKSHEET",
      "ZetaGrow Growth Bundle | File 16 of 28",
      "",
      "1. THE CORE PRODUCT/SERVICE",
      "  What exactly do they get? __________________",
      "  ______________________________",
      "",
      "2. PRICE",
      "  Price: Rs. ______",
      "  Anchor (compare to value): Rs. ______",
      "  Price justification line:",
      "  \"________________________________________\"",
      "",
      "3. BONUSES (stacked value)",
      "  Bonus 1: ______________________________",
      "  Bonus 2: ______________________________",
      "  Bonus 3: ______________________________",
      "",
      "4. GUARANTEE / RISK REVERSAL",
      "  [ ] Money-back (terms): ________________",
      "  [ ] Free trial / sample",
      "  [ ] Satisfaction promise",
      "",
      "5. URGENCY / SCARCITY",
      "  [ ] Deadline: ________________________",
      "  [ ] Limited spots: ____________________",
      "  [ ] Early-bird price",
      "",
      "6. THE OFFER STATEMENT (one paragraph)",
      "  \"For Rs. ______, ________ gets ____________,",
      "  plus ____________, protected by ____________,",
      "  until ____________.\"",
      "",
      "7. OBJECTION ANSWERS",
      "  Too expensive? -> ______________________",
      "  No time?      -> ______________________",
      "  Won't work?   -> ______________________",
      "",
      "RULE: If you cannot write the offer statement in one",
      "sentence, the offer is not ready to advertise.",
    ],
  },
  {
    title: "Landing-Page Checklist",
    slug: "landing-page-checklist",
    type: "pdf",
    description:
      "Pre-launch checklist for any landing page: message matching, single CTA, proof, friction removal, and mobile.",
    sortOrder: 17,
    pdfLines: [
      "LANDING-PAGE CHECKLIST",
      "ZetaGrow Growth Bundle | File 17 of 28",
      "",
      "URL: ______________________________   DATE: ____________",
      "",
      "MESSAGE MATCHING",
      "  [ ] Headline matches the ad's promise",
      "  [ ] Offer on page = offer in ad",
      "  [ ] CTA text matches the ad's CTA",
      "",
      "THE ONE ACTION",
      "  [ ] Exactly one primary CTA (visible without scrolling)",
      "  [ ] No competing links/menus in the decision area",
      "  [ ] CTA repeats after the proof section",
      "",
      "TRUST & PROOF",
      "  [ ] Testimonials / reviews shown",
      "  [ ] Numbers or results shown",
      "  [ ] Money-back / guarantee visible",
      "  [ ] Contact info or about section present",
      "",
      "FRICTION REMOVAL",
      "  [ ] Form asks minimum fields (name + phone ideal)",
      "  [ ] No forced signup before seeing value",
      "  [ ] Mobile view fully tested",
      "  [ ] Loads fast on mobile data",
      "",
      "MEASUREMENT",
      "  [ ] Conversion goal/event installed",
      "  [ ] Source tracking (which ad brought them)",
      "",
      "RULE: The page answers 3 questions - what is this,",
      "why should I care, what do I do now.",
    ],
  },
  {
    title: "Competitor Research Template",
    slug: "competitor-research-template",
    type: "pdf",
    description:
      "Analyze 3 competitors: their offers, hooks, creatives, follow-up, and the gaps you can win with.",
    sortOrder: 18,
    pdfLines: [
      "COMPETITOR RESEARCH TEMPLATE",
      "ZetaGrow Growth Bundle | File 18 of 28",
      "",
      "COMPETITOR 1: ______________________________",
      "  Their offer: ____________________________",
      "  Their price: Rs. ______",
      "  Their hooks/messages: __________________",
      "  Where they advertise: [ ] Meta  [ ] Google  [ ] Organic",
      "  Their follow-up: ________________________",
      "  Their weakness / gap: __________________",
      "",
      "COMPETITOR 2: ______________________________",
      "  Their offer: ____________________________",
      "  Their price: Rs. ______",
      "  Their hooks/messages: __________________",
      "  Where they advertise: [ ] Meta  [ ] Google  [ ] Organic",
      "  Their follow-up: ________________________",
      "  Their weakness / gap: __________________",
      "",
      "COMPETITOR 3: ______________________________",
      "  Their offer: ____________________________",
      "  Their price: Rs. ______",
      "  Their hooks/messages: __________________",
      "  Where they advertise: [ ] Meta  [ ] Google  [ ] Organic",
      "  Their follow-up: ________________________",
      "  Their weakness / gap: __________________",
      "",
      "GAP ANALYSIS - WHAT CAN YOU WIN WITH?",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "TOOLS USED",
      "  [ ] Meta Ad Library  [ ] Google search  [ ] Social browsing",
      "",
      "RULE: Research to learn what the market accepts,",
      "then out-position, not out-spend.",
    ],
  },
  // ── Creative (6) ─────────────────────────────────────────────
  {
    title: "Hook Library",
    slug: "hook-library",
    type: "pdf",
    description:
      "30 proven hook formulas across 6 categories — write your own hooks against each template.",
    sortOrder: 19,
    pdfLines: [
      "HOOK LIBRARY",
      "ZetaGrow Growth Bundle | File 19 of 28",
      "",
      "CURIOSITY HOOKS",
      "  1. \"The one mistake that kills your ads...\"",
      "  2. \"Nobody tells you this about [topic]\"",
      "  3. \"Why [common belief] is wrong\"",
      "  4. \"The reason your [result] never happens\"",
      "  5. \"I tested [X] for 30 days. Here is what happened.\"",
      "  YOURS: ______________________________",
      "",
      "EMOTION HOOKS",
      "  6. \"This is what [pain] actually feels like\"",
      "  7. \"I almost gave up. Then...\"",
      "  8. \"The moment everything changed\"",
      "  9. \"If only someone had told me this earlier\"",
      "  10. \"This is unfair. And it is happening to you.\"",
      "  YOURS: ______________________________",
      "",
      "NOVELTY HOOKS",
      "  11. \"You have never seen [X] done this way\"",
      "  12. \"2026's most underrated skill\"",
      "  13. \"The 30-second trick that does what [X] does\"",
      "  14. \"New algorithm change nobody is talking about\"",
      "  15. \"This format beats every [X] you have tried\"",
      "  YOURS: ______________________________",
      "",
      "RELEVANCE HOOKS",
      "  16. \"If you are a [specific persona], keep watching\"",
      "  17. \"For small businesses in [city] only\"",
      "  18. \"You run ads. This is for you.\"",
      "  19. \"3 signs your [X] is broken\"",
      "  20. \"This is the exact problem you described\"",
      "  YOURS: ______________________________",
      "",
      "PATTERN-INTERRUPT HOOKS",
      "  21. \"Stop scrolling. Seriously.\"",
      "  22. \"(silence) ...now that I have your attention\"",
      "  23. \"POV: you found the answer\"",
      "  24. \"Delete your [X] first. Then listen.\"",
      "  25. \"The most boring advice that actually works\"",
      "  YOURS: ______________________________",
      "",
      "NUMBER HOOKS",
      "  26. \"5 landing page mistakes costing you customers\"",
      "  27. \"Rs. 5,000. 10 days. Here is the plan.\"",
      "  28. \"3 hooks. 3 creatives. 2 offers. 1 winner.\"",
      "  29. \"How 1 campaign made 47 sales\"",
      "  30. \"7 days. One challenge. A complete plan.\"",
      "  YOURS: ______________________________",
      "",
      "RULE: Write 5 hooks per campaign. Test the 2 strongest.",
    ],
  },
  {
    title: "CTA Library",
    slug: "cta-library",
    type: "pdf",
    description:
      "Every CTA phrase organized by goal — clicks, leads, WhatsApp, sales — plus the rules for choosing one.",
    sortOrder: 20,
    pdfLines: [
      "CTA LIBRARY",
      "ZetaGrow Growth Bundle | File 20 of 28",
      "",
      "FOR CLICKS / TRAFFIC",
      "  - Learn More    - See How It Works",
      "  - Read the Guide    - Watch the Demo",
      "  - See Pricing",
      "",
      "FOR LEADS",
      "  - Get the Free Checklist    - Download Now",
      "  - Book a Free Call    - Reserve My Spot",
      "  - Get the Quote",
      "",
      "FOR WHATSAPP / MESSENGER",
      "  - Send WhatsApp Message    - Chat With Us",
      "  - Message Us on WhatsApp    - Get Details on WhatsApp",
      "",
      "FOR SALES",
      "  - Buy Now    - Enroll Today    - Get Started",
      "  - Claim the Discount    - Order Now",
      "  - Start My 7-Day Trial",
      "",
      "FOR RETARGETING (hot audience)",
      "  - Complete Your Order    - Your Discount Awaits",
      "  - Pick Up Where You Left Off",
      "  - Only X Spots Left",
      "",
      "CHOOSING RULES",
      "  1. One CTA per ad and per landing page.",
      "  2. Match the CTA to the objective (sales ads",
      "     should not say Learn More).",
      "  3. Use the same CTA on the ad and the page",
      "     (message matching).",
      "  4. Action verbs only. No dead words like",
      "     'Discover' alone - discover WHAT?",
      "",
      "RULE: The CTA names the next step the customer takes.",
    ],
  },
  {
    title: "Ad-Copy Formulas",
    slug: "ad-copy-formulas",
    type: "pdf",
    description:
      "12 complete copy formulas with fill-in blanks — pick a formula, fill the blanks, test the result.",
    sortOrder: 21,
    pdfLines: [
      "AD-COPY FORMULAS",
      "ZetaGrow Growth Bundle | File 21 of 28",
      "",
      "1. PAIN-BRIDGE:",
      "  \"You know the feeling when [PAIN]. So does",
      "  [AUDIENCE]. [PRODUCT] turns that into [RESULT].\"",
      "",
      "2. BEFORE-AFTER:",
      "  \"Before: [OLD SITUATION]. After: [NEW SITUATION].",
      "  The difference? [ONE CHANGE].\"",
      "",
      "3. CURIOSITY GAP:",
      "  \"[SURPRISING FACT]. Here is why nobody tells",
      "  you this - and what to do about it.\"",
      "",
      "4. LISTICLE:",
      "  \"[N] [TOPIC] mistakes that cost you [PAIN]. Number",
      "  [N-1] is the one everyone makes.\"",
      "",
      "5. OBJECTION CRUSHER:",
      "  \"[OBJECTION]? We hear that a lot. Here is the",
      "  honest answer: [ANSWER].\"",
      "",
      "6. STORY:",
      "  \"[TIME] ago I [STARTING POINT]. [STRUGGLE]. Then",
      "  [TURNING POINT]. Now [RESULT]. This is how.\"",
      "",
      "7. PROOF BY NUMBERS:",
      "  \"[N] customers. [RESULT]. [TIME] in business.",
      "  [STAT]% would do it again. [CTA].\"",
      "",
      "8. DIRECT COMMAND:",
      "  \"[AUDIENCE], read this. If [PROBLEM], then",
      "  [SOLUTION] is built for you. [CTA].\"",
      "",
      "9. MYTH BUST:",
      "  \"[MYTH]. False. The truth: [TRUTH]. That is why",
      "  [PRODUCT] exists.\"",
      "",
      "10. GUARANTEE-LED:",
      "  \"Try [PRODUCT]. If you do not get [RESULT] in",
      "  [TIME], [GUARANTEE]. No questions.\"",
      "",
      "11. SOCIAL PROOF:",
      "  \"[TESTIMONIAL QUOTE]. - [CUSTOMER]. Join [N]",
      "  others who [RESULT]. [CTA].\"",
      "",
      "12. URGENCY:",
      "  \"[OFFER] ends [DATE]. [N] spots left. After that,",
      "  [WHAT CHANGES]. [CTA] now.\"",
      "",
      "RULE: Fill the blanks honestly. The formula organizes",
      "your message; it does not replace truth.",
    ],
  },
  {
    title: "UGC Script Templates",
    slug: "ugc-script-templates",
    type: "pdf",
    description:
      "Ready-to-shoot user-generated content scripts: unboxing, demo, objection, testimonial, and before/after formats.",
    sortOrder: 22,
    pdfLines: [
      "UGC SCRIPT TEMPLATES",
      "ZetaGrow Growth Bundle | File 22 of 28",
      "",
      "FORMAT 1 - THE UNBOXING (0-30 sec)",
      "  0-3s  Hook: \"Okay, this finally arrived...\"",
      "  3-10s Show the package, open it on camera.",
      "  10-20s First impression: \"Wait, this feels solid.\"",
      "  20-30s Close: \"If you want one, link in bio.\"",
      "",
      "FORMAT 2 - THE DEMO (0-40 sec)",
      "  0-3s  Hook: \"Watch what happens in 10 seconds.\"",
      "  3-15s Show the problem state.",
      "  15-30s Apply the product, show the result.",
      "  30-40s Close: \"Same result at home. [CTA].\"",
      "",
      "FORMAT 3 - THE OBJECTION (0-30 sec)",
      "  0-3s  Hook: \"'Too expensive'? Fair. Let me talk.\"",
      "  3-15s Acknowledge, then reframe cost vs value.",
      "  15-25s Give the real number / guarantee.",
      "  25-30s Close: \"Decide for yourself. [CTA].\"",
      "",
      "FORMAT 4 - THE TESTIMONIAL (0-30 sec)",
      "  0-3s  Hook: \"I did not believe it either.\"",
      "  3-15s Before situation and the doubt.",
      "  15-25s The experience and the result.",
      "  25-30s Close: \"Worth it? 100%.\"",
      "",
      "FORMAT 5 - BEFORE/AFTER (0-25 sec)",
      "  0-3s  Hook: \"Day 1 vs Day 30.\"",
      "  3-12s Show Day 1 state honestly.",
      "  12-22s Show Day 30 result.",
      "  22-25s Close: \"[CTA] - same timeline for you.\"",
      "",
      "SHOOTING RULES",
      "  - Natural light facing the speaker, not behind",
      "  - Phone at eye level, horizontal/vertical per platform",
      "  - Hold the product visibly in frame",
      "  - Authentic tone: your real accent, real words",
      "  - Captions on (most watch muted)",
      "",
      "RULE: Real person + real product + one clear promise.",
    ],
  },
  {
    title: "Short-Form Ad Templates",
    slug: "short-form-ad-templates",
    type: "pdf",
    description:
      "Shot-by-shot templates for 6 short-form ad types: hook, problem, proof, offer, CTA for each.",
    sortOrder: 23,
    pdfLines: [
      "SHORT-FORM AD TEMPLATES",
      "ZetaGrow Growth Bundle | File 23 of 28",
      "",
      "TEMPLATE A - THE EDUCATOR (0-45 sec)",
      "  Shot 1 (0-3s): Hook question on screen.",
      "  Shot 2 (3-12s): The problem, honestly named.",
      "  Shot 3 (12-30s): Teach ONE useful thing.",
      "  Shot 4 (30-40s): \"This is what I use.\" Product intro.",
      "  Shot 5 (40-45s): CTA + handle on screen.",
      "",
      "TEMPLATE B - THE FOUNDER (0-40 sec)",
      "  Shot 1 (0-3s): Face to camera, bold claim.",
      "  Shot 2 (3-15s): Why I started this.",
      "  Shot 3 (15-30s): How it solves the problem.",
      "  Shot 4 (30-40s): Offer + guarantee + CTA.",
      "",
      "TEMPLATE C - THE SKIT (0-30 sec)",
      "  Shot 1 (0-3s): Pattern interrupt visual.",
      "  Shot 2 (3-12s): The frustrating scenario.",
      "  Shot 3 (12-22s): The 'aha' with the product.",
      "  Shot 4 (22-30s): Tagline + CTA.",
      "",
      "TEMPLATE D - THE SCROLL-STOPPER (0-20 sec)",
      "  Shot 1 (0-2s): Bold text overlay, minimal visual.",
      "  Shot 2 (2-8s): Fast cuts showing the result.",
      "  Shot 3 (8-15s): How it works in 3 steps.",
      "  Shot 4 (15-20s): CTA button graphic.",
      "",
      "TEMPLATE E - THE ASK (0-25 sec)",
      "  Shot 1 (0-3s): \"Can you do me a favour?\"",
      "  Shot 2 (3-15s): The request + why it matters.",
      "  Shot 3 (15-20s): What they get in return.",
      "  Shot 4 (20-25s): CTA + tag line.",
      "",
      "TEMPLATE F - THE SERIES (0-35 sec, episode N)",
      "  Shot 1 (0-3s): \"Part 3 of 5. [Recall hook].\"",
      "  Shot 2 (3-20s): Deliver part N's value.",
      "  Shot 3 (20-30s): Tease part N+1.",
      "  Shot 4 (30-35s): Follow + CTA.",
      "",
      "RULE: First 3 seconds sell the watch; the last 3",
      "seconds sell the click.",
    ],
  },
  {
    title: "Creative Testing Matrix",
    slug: "creative-testing-matrix",
    type: "pdf",
    description:
      "The 3 hooks x 3 creatives x 2 offers matrix: plan, track, kill, and scale — the core testing system.",
    sortOrder: 24,
    pdfLines: [
      "CREATIVE TESTING MATRIX",
      "ZetaGrow Growth Bundle | File 24 of 28",
      "",
      "THE SYSTEM: 3 HOOKS x 3 CREATIVES x 2 OFFERS",
      "",
      "HOOKS",
      "  H1: ______________________________",
      "  H2: ______________________________",
      "  H3: ______________________________",
      "",
      "CREATIVES",
      "  C1: [ ] Reel  [ ] Static  [ ] Carousel  [ ] UGC",
      "      Description: ______________________",
      "  C2: [ ] Reel  [ ] Static  [ ] Carousel  [ ] UGC",
      "      Description: ______________________",
      "  C3: [ ] Reel  [ ] Static  [ ] Carousel  [ ] UGC",
      "      Description: ______________________",
      "",
      "OFFERS",
      "  O1: ______________________________",
      "  O2: ______________________________",
      "",
      "TEST PLAN (start with 4-6 combos, equal budget)",
      "  Combo 1: H1 + C1 + O1   Budget: Rs. ______",
      "  Combo 2: H2 + C2 + O1   Budget: Rs. ______",
      "  Combo 3: H3 + C3 + O2   Budget: Rs. ______",
      "  Combo 4: H1 + C2 + O2   Budget: Rs. ______",
      "  Combo 5: H2 + C3 + O1   Budget: Rs. ______",
      "  Combo 6: H3 + C1 + O2   Budget: Rs. ______",
      "",
      "RESULTS TABLE (after 3-5 days)",
      "  | Combo | CTR | CPL/CPA | ROAS | Verdict |",
      "  |-------|-----|---------|------|---------|",
      "  | 1     |     |         |      |         |",
      "  | 2     |     |         |      |         |",
      "  | 3     |     |         |      |         |",
      "  | 4     |     |         |      |         |",
      "  | 5     |     |         |      |         |",
      "  | 6     |     |         |      |         |",
      "",
      "DECISIONS",
      "  - Kill the bottom half after 3-5 days.",
      "  - Double budget on the top 1-2 only.",
      "  - Iterate: same hook, new creative (or reverse).",
      "  - Never judge a creative in under 3 days.",
      "",
      "RULE: Creative wins campaigns. Test like a scientist,",
      "not a gambler.",
    ],
  },
  // ── Analytics (4) ────────────────────────────────────────────
  {
    title: "Campaign Reporting Template",
    slug: "campaign-reporting-template",
    type: "pdf",
    description:
      "The weekly one-page report: spend, clicks, conversions, costs, ROAS, creative performance, and next actions.",
    sortOrder: 25,
    pdfLines: [
      "CAMPAIGN REPORTING TEMPLATE",
      "ZetaGrow Growth Bundle | File 25 of 28",
      "",
      "PERIOD: ____________ to ____________",
      "CAMPAIGN(S): ______________________________",
      "",
      "TOP-LINE METRICS",
      "  Spend: Rs. ____________",
      "  Impressions: ____________",
      "  Reach: ____________   Frequency: ____________",
      "  Clicks: ____________   CTR: ____%",
      "  CPC: Rs. ______   CPM: Rs. ______",
      "  Leads: ____________   CPL: Rs. ______",
      "  Sales: ____________   CPA: Rs. ______",
      "  Revenue: Rs. ____________   ROAS: ____x",
      "",
      "CREATIVE PERFORMANCE (best to worst)",
      "  1. ________________  CTR ____%  CPA Rs. ______",
      "  2. ________________  CTR ____%  CPA Rs. ______",
      "  3. ________________  CTR ____%  CPA Rs. ______",
      "  4. ________________  CTR ____%  CPA Rs. ______",
      "",
      "DIAGNOSIS (use the framework)",
      "  [ ] Low CTR -> creative problem, change hooks",
      "  [ ] No conversions -> landing page/offer problem",
      "  [ ] Expensive conversions -> targeting/bidding",
      "  [ ] High frequency -> fatigue, refresh creative",
      "",
      "NEXT ACTIONS (this week)",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "",
      "LEARNING (one line for the team)",
      "  \"________________________________________\"",
      "",
      "RULE: Compare to last week, not last year. One page,",
      "one clear set of next actions.",
    ],
  },
  {
    title: "KPI Tracker",
    slug: "kpi-tracker",
    type: "pdf",
    description:
      "Track your 5 core metrics week by week: CTR, CPL, CPA, ROAS, and conversion rate with thresholds.",
    sortOrder: 26,
    pdfLines: [
      "KPI TRACKER",
      "ZetaGrow Growth Bundle | File 26 of 28",
      "",
      "CAMPAIGN: ______________________________",
      "GOAL: ______________________________",
      "THRESHOLDS: CTR ____%  |  CPL Rs. ____  |",
      "CPA Rs. ____  |  ROAS ____x  |  Conv ____%",
      "",
      "WEEK 1   Date: ____________",
      "  CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  Conv ____%  Spend Rs. ____",
      "  Verdict: [ ] On track  [ ] Fix [ ] Kill",
      "",
      "WEEK 2   Date: ____________",
      "  CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  Conv ____%  Spend Rs. ____",
      "  Verdict: [ ] On track  [ ] Fix [ ] Kill",
      "",
      "WEEK 3   Date: ____________",
      "  CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  Conv ____%  Spend Rs. ____",
      "  Verdict: [ ] On track  [ ] Fix [ ] Kill",
      "",
      "WEEK 4   Date: ____________",
      "  CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  Conv ____%  Spend Rs. ____",
      "  Verdict: [ ] On track  [ ] Fix [ ] Kill",
      "",
      "WEEK 5   Date: ____________",
      "  CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  Conv ____%  Spend Rs. ____",
      "  Verdict: [ ] On track  [ ] Fix [ ] Kill",
      "",
      "WEEK 6   Date: ____________",
      "  CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  Conv ____%  Spend Rs. ____",
      "  Verdict: [ ] On track  [ ] Fix [ ] Kill",
      "",
      "TREND NOTES",
      "  Week-to-week direction of CPA: up / down / flat",
      "  Week-to-week direction of CTR: up / down / flat",
      "",
      "RULE: Kill below threshold for 2 straight weeks.",
      "Double the winner that beats threshold 2 weeks.",
    ],
  },
  {
    title: "Weekly Optimization Checklist",
    slug: "weekly-optimization-checklist",
    type: "pdf",
    description:
      "The repeatable Monday ritual: review KPIs, pause losers, scale winners, launch one new test, log learnings.",
    sortOrder: 27,
    pdfLines: [
      "WEEKLY OPTIMIZATION CHECKLIST",
      "ZetaGrow Growth Bundle | File 27 of 28",
      "",
      "WEEK OF: ____________   ACCOUNT: ____________",
      "",
      "MONDAY - REVIEW",
      "  [ ] KPIs compared vs last week (not last year)",
      "  [ ] Spend vs plan checked (on pace? over/under?)",
      "  [ ] Creative performance sorted best to worst",
      "",
      "TUESDAY - DECIDE",
      "  [ ] Paused/killed anything below threshold for 5+",
      "      days (no emotional defending)",
      "  [ ] Budget doubled on top 1-2 performers only",
      "      (+20-30% steps, never overnight doubles)",
      "",
      "WEDNESDAY - TEST",
      "  [ ] One new test launched (ONE variable changed)",
      "  [ ] Test budget allocated (equal share per combo)",
      "",
      "THURSDAY - FOLLOW-UP",
      "  [ ] Lead follow-up speed verified (minutes, not days)",
      "  [ ] Landing page checked on mobile data",
      "  [ ] Tracking events firing correctly",
      "",
      "FRIDAY - LEARN",
      "  [ ] Learnings logged in KPI tracker",
      "  [ ] Winner's hook/angle noted for reuse",
      "  [ ] Next week's 1-page report drafted",
      "",
      "SATURDAY/SUNDAY - REST",
      "  [ ] Ads run without you. That is the point of a system.",
      "",
      "RULE: Optimization is a weekly ritual, not an emergency.",
    ],
  },
  {
    title: "ROAS/CPA Analysis Sheet",
    slug: "roas-cpa-analysis-sheet",
    type: "pdf",
    description:
      "The money sheet: revenue, spend, ROAS and CPA across campaigns, channels, and months — plus breakeven math.",
    sortOrder: 28,
    pdfLines: [
      "ROAS / CPA ANALYSIS SHEET",
      "ZetaGrow Growth Bundle | File 28 of 28",
      "",
      "BREAKEVEN MATH (do this once per product)",
      "  Price: Rs. ______",
      "  Margin per sale: Rs. ______",
      "  Breakeven CPA = Margin: Rs. ______",
      "  Breakeven ROAS = Price / Margin: ____x",
      "  (Below this CPA you lose money on every sale)",
      "",
      "BY CAMPAIGN (this month)",
      "  | Campaign | Spend | Revenue | ROAS | CPA |",
      "  |----------|-------|---------|------|-----|",
      "  |          |       |         |      |     |",
      "  |          |       |         |      |     |",
      "  |          |       |         |      |     |",
      "",
      "BY CHANNEL (this month)",
      "  | Channel | Spend | Revenue | ROAS | CPA |",
      "  |---------|-------|---------|------|-----|",
      "  | Meta    |       |         |      |     |",
      "  | Google  |       |         |      |     |",
      "  | Organic |       |         |      |     |",
      "",
      "MONTHLY TREND",
      "  | Month | Spend | Revenue | ROAS | CPA |",
      "  |-------|-------|---------|------|-----|",
      "  |       |       |         |      |     |",
      "  |       |       |         |      |     |",
      "  |       |       |         |      |     |",
      "",
      "READING THE SHEET",
      "  - ROAS below breakeven? Check CPA vs margin first.",
      "  - CPA rising 3 weeks in a row? Creative fatigue",
      "    or audience saturation - refresh, don't panic.",
      "  - One channel consistently below breakeven?",
      "    Reduce spend there, scale the winner.",
      "",
      "RULE: ROAS without margin math is decoration.",
      "Know your breakeven before you spend a rupee.",
    ],
  },
];