/**
 * Digital Business Pro (₹14,000) — 40-file Pro Resource Library.
 * Each resource is generated as a PDF and stored in Convex.
 */

export interface ProResourceDef {
  title: string;
  slug: string;
  type: "pdf";
  description: string;
  sortOrder: number;
  pdfLines: string[];
}

export const PRO_RESOURCES: ProResourceDef[] = [
  // ── Business (7) ────────────────────────────────────────────
  {
    title: "Business Plan Template",
    slug: "business-plan-template",
    type: "pdf",
    description:
      "The one-page business plan: opportunity, solution, customer, economics, and 90-day milestones.",
    sortOrder: 1,
    pdfLines: [
      "BUSINESS PLAN TEMPLATE",
      "ZetaGrow Pro Resource Library | File 1 of 40",
      "",
      "1. OPPORTUNITY",
      "  Problem: ______________________________",
      "  Evidence of demand: ____________________",
      "  Market size (est.): ____________________",
      "",
      "2. SOLUTION",
      "  Offer: ________________________________",
      "  Positioning: __________________________",
      "  Revenue model: ________________________",
      "",
      "3. CUSTOMER",
      "  Persona: ______________________________",
      "  Buying moment: ________________________",
      "  Channels: ______________________________",
      "",
      "4. ECONOMICS",
      "  Price: Rs. ______  Margin: ______%",
      "  Break-even CPA: Rs. ______",
      "  LTV : CAC target: ______x",
      "",
      "5. 90-DAY MILESTONES",
      "  Month 1: ______________________________",
      "  Month 2: ______________________________",
      "  Month 3: ______________________________",
      "",
      "RULE: One page. If it does not fit, the plan is",
      "not clear.",
    ],
  },
  {
    title: "Business Model Canvas",
    slug: "business-model-canvas",
    type: "pdf",
    description:
      "The classic canvas: value proposition, segments, channels, relationships, revenue, resources, activities, partners, costs.",
    sortOrder: 2,
    pdfLines: [
      "BUSINESS MODEL CANVAS",
      "ZetaGrow Pro Resource Library | File 2 of 40",
      "",
      "KEY PARTNERS",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "KEY ACTIVITIES",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "KEY RESOURCES",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "VALUE PROPOSITION",
      "  \"For [customer], [offer] is the [category]",
      "  that [outcome], unlike [alternative],",
      "  because [reason].\"",
      "",
      "CUSTOMER RELATIONSHIPS",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "CHANNELS",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "CUSTOMER SEGMENTS",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "REVENUE STREAMS",
      "  1. ____________________ 2. ____________________",
      "  3. ____________________",
      "",
      "COST STRUCTURE",
      "  Fixed: ______________________________",
      "  Variable: ______________________________",
      "",
      "RULE: Fill the value proposition first - everything",
      "else serves it.",
    ],
  },
  {
    title: "Offer Builder",
    slug: "offer-builder",
    type: "pdf",
    description:
      "The complete offer system: packages, upsells, cross-sells, bundles, bonuses, guarantee, and the offer statement.",
    sortOrder: 3,
    pdfLines: [
      "OFFER BUILDER",
      "ZetaGrow Pro Resource Library | File 3 of 40",
      "",
      "1. OUTCOME",
      "  Measured result: \"____________________\"",
      "  Timeline: ______________________________",
      "",
      "2. PACKAGES",
      "  Basic: Rs. ____ | Standard: Rs. ____ (recommended)",
      "  Premium: Rs. ____",
      "  What each includes: ____________________",
      "",
      "3. UPSELL (after purchase)",
      "  Next step: ______________________________",
      "  When: ______________________________",
      "",
      "4. CROSS-SELL",
      "  Related product: ________________________",
      "  When: ______________________________",
      "",
      "5. BUNDLE",
      "  Contents: ______________________________",
      "  Bundle price: Rs. ____ (vs Rs. ____ separately)",
      "",
      "6. BONUSES",
      "  1. ____________________ 2. ____________________",
      "",
      "7. RISK REDUCTION",
      "  Guarantee: ______________________________",
      "",
      "8. OFFER STATEMENT (one paragraph)",
      "  \"For Rs. ____, [customer] gets ________,",
      "  plus ________, protected by ________,",
      "  until ________.\"",
      "",
      "9. OFFER TEST PLAN",
      "  Variable to test: ________ | When: ________",
      "",
      "RULE: The offer is the highest-leverage variable.",
    ],
  },
  {
    title: "Pricing Calculator",
    slug: "pricing-calculator",
    type: "pdf",
    description:
      "Value-based pricing with anchor, tiers, margin check, and price-increase planning.",
    sortOrder: 4,
    pdfLines: [
      "PRICING CALCULATOR",
      "ZetaGrow Pro Resource Library | File 4 of 40",
      "",
      "1. COST BASIS",
      "  Cost to deliver: Rs. ______",
      "  Fixed costs / month: Rs. ______",
      "",
      "2. OUTCOME VALUE",
      "  Value gained by customer / year: Rs. ______",
      "  Cost of the problem / year: Rs. ______",
      "",
      "3. VALUE-BASED PRICE RANGE",
      "  Rs. ______ to Rs. ______",
      "  (10-20% of outcome value is common)",
      "",
      "4. ANCHOR",
      "  Reference value: Rs. ______  Your price: Rs. ______",
      "",
      "5. TIERS",
      "  Basic Rs. ____ / Standard Rs. ____ / Premium Rs. ____",
      "",
      "6. MARGIN CHECK",
      "  Price - delivery cost = margin: Rs. ______",
      "  Margin %: ______% (healthy: 60%+)",
      "",
      "7. PRICE INCREASE PLAN",
      "  Current: Rs. ____  Next: Rs. ____  Date: ________",
      "",
      "8. BREAK-EVEN",
      "  Break-even CPA = margin: Rs. ______",
      "  Break-even ROAS = price / margin: ______x",
      "",
      "RULE: Price by outcome. Test price changes; measure",
      "conversion each time.",
    ],
  },
  {
    title: "Customer Persona",
    slug: "customer-persona",
    type: "pdf",
    description:
      "Full ICP worksheet: demographics, goals, pains (3 layers), buying moment, objections, channels.",
    sortOrder: 5,
    pdfLines: [
      "CUSTOMER PERSONA",
      "ZetaGrow Pro Resource Library | File 5 of 40",
      "",
      "PERSONA NAME: ______________________________",
      "",
      "DEMOGRAPHICS",
      "  Age: ________  Location: ________  Income: ________",
      "  Role: ________________________________",
      "",
      "GOALS",
      "  1. ______________________________ 2. ______________",
      "  3. ______________________________",
      "",
      "PAINS",
      "  Surface: ______________________________",
      "  Root: ________________________________",
      "  Emotional: ____________________________",
      "",
      "BUYING MOMENT",
      "  What event makes them buy NOW? ______________",
      "",
      "OBJECTIONS",
      "  1. ______________________________ 2. ______________",
      "  3. ______________________________",
      "",
      "CHANNELS",
      "  [ ] Instagram  [ ] YouTube  [ ] WhatsApp",
      "  [ ] Google  [ ] LinkedIn  [ ] Communities",
      "",
      "ONE-SENTENCE PROFILE",
      "  \"________ is a ________ who wants ________",
      "  but struggles with ________.\"",
      "",
      "RULE: Research the language; never invent it.",
    ],
  },
  {
    title: "Competitor Analysis",
    slug: "competitor-analysis",
    type: "pdf",
    description:
      "Five-competitor map: offer, price, positioning, channels, strengths, weaknesses, and the gaps you own.",
    sortOrder: 6,
    pdfLines: [
      "COMPETITOR ANALYSIS",
      "ZetaGrow Pro Resource Library | File 6 of 40",
      "",
      "COMPETITOR 1: ______________________________",
      "  Offer: ________  Price: Rs. ____  Positioning: ________",
      "  Channels: ________  Strengths: ________  Weak: ________",
      "",
      "COMPETITOR 2: ______________________________",
      "  Offer: ________  Price: Rs. ____  Positioning: ________",
      "  Channels: ________  Strengths: ________  Weak: ________",
      "",
      "COMPETITOR 3: ______________________________",
      "  Offer: ________  Price: Rs. ____  Positioning: ________",
      "  Channels: ________  Strengths: ________  Weak: ________",
      "",
      "COMPETITOR 4: ______________________________",
      "  Offer: ________  Price: Rs. ____  Positioning: ________",
      "  Channels: ________  Strengths: ________  Weak: ________",
      "",
      "COMPETITOR 5: ______________________________",
      "  Offer: ________  Price: Rs. ____  Positioning: ________",
      "  Channels: ________  Strengths: ________  Weak: ________",
      "",
      "GAPS (segments they serve poorly)",
      "  1. ______________________________ 2. ______________",
      "  3. ______________________________",
      "",
      "YOUR POSITIONING (owns one gap)",
      "  \"________________________________________\"",
      "",
      "RULE: Compete where they are weak, not where they",
      "are strong.",
    ],
  },
  {
    title: "Market Research Guide",
    slug: "market-research-guide",
    type: "pdf",
    description:
      "The research workflow: market size, growth, structure, interviews, review mining, and evidence log.",
    sortOrder: 7,
    pdfLines: [
      "MARKET RESEARCH GUIDE",
      "ZetaGrow Pro Resource Library | File 7 of 40",
      "",
      "1. MARKET SIZE",
      "  Top-down (buyers x spend): ________",
      "  Bottom-up (competitor revenue): ________",
      "  Verdict: ______________________________",
      "",
      "2. MARKET GROWTH",
      "  Growing / flat / shrinking? Evidence: ________",
      "",
      "3. MARKET STRUCTURE",
      "  Few big players or fragmented? ________",
      "  (Fragmented = best for newcomers)",
      "",
      "4. INTERVIEWS (5-10)",
      "  Questions: last attempt, what they spent,",
      "  what stopped them, desired outcome.",
      "  Key quotes:",
      "  - \"________________________\"",
      "  - \"________________________\"",
      "",
      "5. REVIEW MINING (20+)",
      "  Top 5 pains with counts:",
      "  1. ________ (__)  2. ________ (__)  3. ________ (__)",
      "  4. ________ (__)  5. ________ (__)",
      "",
      "6. EVIDENCE LOG (every claim needs a source)",
      "  Claim -> source: ______________________",
      "",
      "7. RESEARCH OUTPUT",
      "  Problem statement: \"____________________\"",
      "  Willingness-to-pay signals: ______________",
      "",
      "RULE: Research ends with a problem statement in",
      "the customer's words.",
    ],
  },
  // ── Marketing (5) ───────────────────────────────────────────
  {
    title: "Complete Marketing Strategy",
    slug: "complete-marketing-strategy",
    type: "pdf",
    description:
      "The one-page marketing strategy: target, message, channels, budget split, funnel, and measurement.",
    sortOrder: 8,
    pdfLines: [
      "COMPLETE MARKETING STRATEGY",
      "ZetaGrow Pro Resource Library | File 8 of 40",
      "",
      "1. TARGET",
      "  Who: ________________________________",
      "  Their problem: ________________________",
      "",
      "2. MESSAGE (one sentence)",
      "  \"________________________________________\"",
      "",
      "3. CHANNEL MIX",
      "  Organic: content (____%), SEO (____%)",
      "  Paid: Meta (____%), Google (____%)",
      "  Retention: email/WhatsApp (____%)",
      "",
      "4. BUDGET ALLOCATION (monthly)",
      "  Total: Rs. ______",
      "  Prospecting: ____%  Retargeting: ____%  Testing: ____%",
      "",
      "5. THE FUNNEL (archetype)",
      "  ________ -> ________ -> ________ -> ________",
      "",
      "6. OFFER SYSTEM",
      "  Core: ________  Upsell: ________  Bundle: ________",
      "",
      "7. MEASUREMENT",
      "  KPIs: CTR ____%  CPL Rs. ____  CPA Rs. ____",
      "  ROAS ____x  LTV:CAC ____x",
      "  Review cadence: weekly / monthly",
      "",
      "8. THIS QUARTER'S ONE FOCUS",
      "  ________________________________________",
      "",
      "RULE: Strategy = target + message + channels +",
      "measurement. Everything else is tactics.",
    ],
  },
  {
    title: "Funnel Templates",
    slug: "funnel-templates",
    type: "pdf",
    description:
      "All four funnel archetypes with stage-by-stage automation handoffs: lead gen, e-commerce, creator, service.",
    sortOrder: 9,
    pdfLines: [
      "FUNNEL TEMPLATES",
      "ZetaGrow Pro Resource Library | File 9 of 40",
      "",
      "FUNNEL 1 - LEAD GENERATION",
      "  Ad -> Landing Page -> Lead -> Follow-up -> Sales",
      "  Ad: leads objective | Page: quote/magnet form",
      "  Handoff: form -> CRM auto-reply -> call < 30 min",
      "  Metrics: CPL, lead-to-call, call-to-client",
      "",
      "FUNNEL 2 - E-COMMERCE",
      "  Ad -> Product -> Checkout -> Purchase -> Retarget",
      "  Ad: sales objective | Page: product page",
      "  Handoff: checkout -> order confirm -> delivery updates",
      "  Retarget: cart abandoners + non-buyers",
      "  Metrics: CTR, add-to-cart, ROAS, repeat rate",
      "",
      "FUNNEL 3 - CREATOR",
      "  Content -> Audience -> Magnet -> Email -> Product",
      "  Content: 3-5 pieces/week | Magnet: checklist/guide",
      "  Handoff: download -> welcome -> nurture -> launch",
      "  Metrics: capture rate, open rate, launch conversion",
      "",
      "FUNNEL 4 - SERVICE BUSINESS",
      "  Content/Ads -> Inquiry -> Qualify -> Call -> Proposal",
      "  Qualify: fit, budget, timing | Proposal: one page",
      "  Handoff: proposal -> follow-ups -> close -> onboard",
      "  Metrics: inquiries, qualified rate, win rate",
      "",
      "YOUR FUNNEL (pick one, draw stages + metrics)",
      "  ________________________________________",
      "",
      "RULE: One goal per stage; every stage feeds the next",
      "automatically.",
    ],
  },
  {
    title: "Campaign Planners",
    slug: "campaign-planners",
    type: "pdf",
    description:
      "The combined campaign planning kit: objective, audiences, budget split, creative matrix, tracking, decision rules.",
    sortOrder: 10,
    pdfLines: [
      "CAMPAIGN PLANNERS",
      "ZetaGrow Pro Resource Library | File 10 of 40",
      "",
      "CAMPAIGN NAME: ______________________________",
      "",
      "1. OBJECTIVE (one only)",
      "  [ ] Sales  [ ] Leads  [ ] Traffic  [ ] Awareness",
      "",
      "2. AUDIENCES",
      "  Cold: ______________________________",
      "  Warm: ______________________________",
      "  Hot: ______________________________",
      "  Exclusions: ______________________________",
      "",
      "3. BUDGET SPLIT",
      "  Total: Rs. ______",
      "  Prospecting ____%  Retargeting ____%  Testing ____%",
      "",
      "4. CREATIVE MATRIX",
      "  Hooks: 1.________ 2.________ 3.________",
      "  Formats: 1.________ 2.________ 3.________",
      "  Offers: 1.________ 2.________",
      "  Combos: ______________________________",
      "",
      "5. TRACKING",
      "  Events: ________________  Verified: [ ]",
      "",
      "6. DECISION RULES (written BEFORE launch)",
      "  Kill if: ________________ after ____ days",
      "  Scale if: ________________ after ____ days",
      "  Review date: ____________",
      "",
      "RULE: Decisions written in advance remove emotion",
      "from optimization.",
    ],
  },
  {
    title: "Creative Testing Framework",
    slug: "creative-testing-framework",
    type: "pdf",
    description:
      "The professional testing system: 3x3x2 matrix, test rules, kill/scale thresholds, and iteration loops.",
    sortOrder: 11,
    pdfLines: [
      "CREATIVE TESTING FRAMEWORK",
      "ZetaGrow Pro Resource Library | File 11 of 40",
      "",
      "THE MATRIX: 3 HOOKS x 3 CREATIVES x 2 OFFERS",
      "",
      "HOOKS",
      "  H1: ______________________________",
      "  H2: ______________________________",
      "  H3: ______________________________",
      "",
      "CREATIVES",
      "  C1: ________  C2: ________  C3: ________",
      "",
      "OFFERS",
      "  O1: ______________________________",
      "  O2: ______________________________",
      "",
      "TEST PLAN (4-6 combos, equal budget)",
      "  1. H1+C1+O1  Rs. ____  4. H1+C2+O2  Rs. ____",
      "  2. H2+C2+O1  Rs. ____  5. H2+C3+O1  Rs. ____",
      "  3. H3+C3+O2  Rs. ____  6. H3+C1+O2  Rs. ____",
      "",
      "RESULTS (after 3-5 days)",
      "  | Combo | CTR | CPL/CPA | ROAS | Verdict |",
      "  |-------|-----|---------|------|---------|",
      "  |       |     |         |      |         |",
      "  |       |     |         |      |         |",
      "  |       |     |         |      |         |",
      "",
      "RULES",
      "  - Kill bottom half after 3-5 days",
      "  - Double top 1-2 only (+20-30% steps)",
      "  - Iterate: keep hook, change body/format/offer",
      "  - One variable per test",
      "",
      "RULE: Creative wins campaigns; test like a",
      "scientist, not a gambler.",
    ],
  },
  {
    title: "Marketing Calendar",
    slug: "marketing-calendar",
    type: "pdf",
    description:
      "The weekly grid: day x pillar x format x platform x CTA, plus the batch production rhythm.",
    sortOrder: 12,
    pdfLines: [
      "MARKETING CALENDAR",
      "ZetaGrow Pro Resource Library | File 12 of 40",
      "",
      "WEEK OF: ____________",
      "",
      "| Day | Pillar | Format | Platform | CTA |",
      "|-----|--------|--------|----------|-----|",
      "| Mon |        |        |          |     |",
      "| Tue |        |        |          |     |",
      "| Wed |        |        |          |     |",
      "| Thu |        |        |          |     |",
      "| Fri |        |        |          |     |",
      "| Sat |        |        |          |     |",
      "| Sun |        |        |          |     |",
      "",
      "PILLARS",
      "  1. ________ 2. ________ 3. ________ 4. ________",
      "",
      "BATCH RHYTHM",
      "  Planning: 1h (Monday) - 10-20 ideas",
      "  Production: 1 session - record everything",
      "  Editing: 1 session - cut, caption, thumbnail",
      "  Scheduling: 30 min - calendar + automation",
      "",
      "CONTENT ENGINE (one idea -> six pieces)",
      "  Long video -> 5 shorts -> 3 posts -> 1 article -> 1 email",
      "",
      "MONTHLY REVIEW",
      "  Winners: ______________________________",
      "  Kill: ________________________________",
      "  Next month's themes: __________________",
      "",
      "RULE: 80% teaches, 20% sells. Batch or burn out.",
    ],
  },
  // ── Ads (6) ─────────────────────────────────────────────────
  {
    title: "Meta Campaign Template",
    slug: "meta-campaign-template",
    type: "pdf",
    description:
      "Professional Meta campaign plan: architecture, audiences, budget split, creative matrix, tracking, diagnosis checklist.",
    sortOrder: 13,
    pdfLines: [
      "META CAMPAIGN TEMPLATE",
      "ZetaGrow Pro Resource Library | File 13 of 40",
      "",
      "CAMPAIGN NAME: ______________________________",
      "  (Platform-Objective-Audience-Creative-Offer)",
      "",
      "1. OBJECTIVE",
      "  [ ] Sales  [ ] Leads  [ ] Traffic  [ ] Awareness",
      "",
      "2. AUDIENCES",
      "  Cold: [ ] Broad  [ ] Interests: ______________",
      "  Custom: [ ] Video 50%  [ ] Engaged  [ ] Visitors",
      "  Lookalike: source + size: ______________",
      "  Exclusions: ______________________________",
      "",
      "3. BUDGET ALLOCATION",
      "  Total: Rs. ______",
      "  Cold ____%  Retarget ____%  Testing ____%",
      "",
      "4. CREATIVE MATRIX",
      "  Hooks: 1.________ 2.________ 3.________",
      "  Formats: 1.________ 2.________ 3.________",
      "  Offers: 1.________ 2.________",
      "",
      "5. TRACKING",
      "  Pixel + CAPI: [ ]  Events verified: [ ]",
      "",
      "6. DECISION RULES",
      "  Kill: CTR < ____% or CPA > Rs. ____ after 5 days",
      "  Scale: CPA < Rs. ____ for 3 days, +20-30%",
      "",
      "7. DIAGNOSIS CHECKLIST",
      "  [ ] Tracking real?  [ ] CTR low? (creative)",
      "  [ ] No conversions? (page/offer)",
      "  [ ] Costs high? (CPC/CPM/exclusions)",
      "  [ ] Frequency > 3-4? (fatigue)",
      "",
      "RULE: Run the diagnosis in order; change one thing.",
    ],
  },
  {
    title: "Google Ads Template",
    slug: "google-ads-template",
    type: "pdf",
    description:
      "Professional Google Ads structure: campaigns, ad groups, keywords, negatives, ad copy, tracking, weekly ritual.",
    sortOrder: 14,
    pdfLines: [
      "GOOGLE ADS TEMPLATE",
      "ZetaGrow Pro Resource Library | File 14 of 40",
      "",
      "CAMPAIGN: ______________________________",
      "  Type: [ ] Search  [ ] Shopping  [ ] YouTube  [ ] Display",
      "",
      "AD GROUP 1 - THEME: ______________________",
      "  Keywords (5-15):",
      "  - ____________________  - ____________________",
      "  - ____________________  - ____________________",
      "",
      "AD GROUP 2 - THEME: ______________________",
      "  Keywords:",
      "  - ____________________  - ____________________",
      "  - ____________________  - ____________________",
      "",
      "NEGATIVE KEYWORDS",
      "  - free  - job  - salary  - tutorial",
      "  - ____________________  - ____________________",
      "",
      "AD COPY (RSA: 8+ headlines, 4+ descriptions)",
      "  H1 (keyword+offer): ____________________",
      "  H2 (differentiator): ____________________",
      "  H3 (proof): ____________________",
      "  D1 (benefit + CTA): ____________________",
      "",
      "LANDING PAGES (message matching)",
      "  URL: ________________________________",
      "  Same promise in H1: [ ]  Price visible: [ ]",
      "",
      "CONVERSION TRACKING",
      "  Actions: ________________  Values: [ ]",
      "",
      "WEEKLY RITUAL",
      "  [ ] Search terms report -> promote winners,",
      "      add negatives",
      "  [ ] Bid adjustments on winners/losers",
      "  [ ] Quality score review",
      "",
      "RULE: Precision beats volume in Google Ads.",
    ],
  },
  {
    title: "Ad-Copy Library",
    slug: "ad-copy-library",
    type: "pdf",
    description:
      "12 proven copy formulas with blanks, plus hook categories and CTA rules for professional testing.",
    sortOrder: 15,
    pdfLines: [
      "AD-COPY LIBRARY",
      "ZetaGrow Pro Resource Library | File 15 of 40",
      "",
      "1. PAIN-BRIDGE",
      "  \"You know the feeling when [PAIN]. [PRODUCT]",
      "  turns that into [RESULT].\"",
      "",
      "2. BEFORE-AFTER",
      "  \"Before: [OLD]. After: [NEW]. The difference?",
      "  [ONE CHANGE].\"",
      "",
      "3. CURIOSITY GAP",
      "  \"[FACT]. Here is why nobody tells you this -",
      "  and what to do about it.\"",
      "",
      "4. LISTICLE",
      "  \"[N] mistakes that cost you [PAIN]. Number [N-1]",
      "  is the one everyone makes.\"",
      "",
      "5. OBJECTION CRUSHER",
      "  \"[OBJECTION]? Fair. Here is the honest answer:",
      "  [ANSWER].\"",
      "",
      "6. STORY",
      "  \"[TIME] ago I [START]. [STRUGGLE]. Then [TURN].",
      "  Now [RESULT]. This is how.\"",
      "",
      "7. PROOF BY NUMBERS",
      "  \"[N] customers. [RESULT]. [TIME] in business.",
      "  [STAT]% would repeat. [CTA].\"",
      "",
      "8. DIRECT COMMAND",
      "  \"[AUDIENCE], read this. If [PROBLEM], then",
      "  [SOLUTION] is built for you.\"",
      "",
      "9. MYTH BUST",
      "  \"[MYTH]. False. The truth: [TRUTH]. That is why",
      "  [PRODUCT] exists.\"",
      "",
      "10. GUARANTEE-LED",
      "  \"Try [PRODUCT]. No [RESULT] in [TIME]?",
      "  [GUARANTEE]. No questions.\"",
      "",
      "11. SOCIAL PROOF",
      "  \"[QUOTE]. - [CUSTOMER]. Join [N] others who",
      "  [RESULT]. [CTA].\"",
      "",
      "12. URGENCY",
      "  \"[OFFER] ends [DATE]. [N] spots left.\"",
      "",
      "CTA RULES: one CTA per ad; action verb + outcome;",
      "match the ad's CTA on the landing page.",
      "",
      "RULE: Fill blanks honestly. Formulas organize,",
      "they do not replace truth.",
    ],
  },
  {
    title: "Creative Briefs",
    slug: "creative-briefs",
    type: "pdf",
    description:
      "The one-page creative brief: goal, audience, hook, message, proof, offer, format, and success criteria.",
    sortOrder: 16,
    pdfLines: [
      "CREATIVE BRIEFS",
      "ZetaGrow Pro Resource Library | File 16 of 40",
      "",
      "CREATIVE NAME: ______________________________",
      "  Campaign / ad set: ______________________",
      "",
      "1. GOAL",
      "  What should this ad achieve? ____________",
      "",
      "2. AUDIENCE",
      "  Who sees it (temperature + description):",
      "  ________________________________________",
      "",
      "3. HOOK (first 3 seconds / first line)",
      "  \"________________________________________\"",
      "",
      "4. CORE MESSAGE (one sentence)",
      "  \"________________________________________\"",
      "",
      "5. PROOF",
      "  [ ] Numbers  [ ] Testimonial  [ ] Demo  [ ] Before/After",
      "  Detail: ______________________________",
      "",
      "6. OFFER & CTA",
      "  Offer: ______________________________",
      "  CTA button: ______________________________",
      "",
      "7. FORMAT & VISUAL",
      "  [ ] Reel  [ ] Static  [ ] Carousel  [ ] UGC  [ ] Founder",
      "  First frame: ______________________________",
      "",
      "8. SUCCESS CRITERIA",
      "  CTR > ____%  /  completion > ____%",
      "  Review after: ____ days  Budget: Rs. ______",
      "",
      "RULE: One brief per creative. No brief, no ad.",
    ],
  },
  {
    title: "Testing Matrices",
    slug: "testing-matrices",
    type: "pdf",
    description:
      "The 3x3x2 testing matrix with a 6-combo test plan and results table for kill/scale decisions.",
    sortOrder: 17,
    pdfLines: [
      "TESTING MATRICES",
      "ZetaGrow Pro Resource Library | File 17 of 40",
      "",
      "THE SYSTEM: 3 HOOKS x 3 CREATIVES x 2 OFFERS",
      "",
      "HOOKS",
      "  H1: ______________________________",
      "  H2: ______________________________",
      "  H3: ______________________________",
      "",
      "CREATIVES",
      "  C1: ______________________________",
      "  C2: ______________________________",
      "  C3: ______________________________",
      "",
      "OFFERS",
      "  O1: ______________________________",
      "  O2: ______________________________",
      "",
      "TEST PLAN (equal budgets, 3-5 days)",
      "  1. H1 + C1 + O1 | Rs. ______ | Start: ________",
      "  2. H2 + C2 + O1 | Rs. ______ | Start: ________",
      "  3. H3 + C3 + O2 | Rs. ______ | Start: ________",
      "  4. H1 + C2 + O2 | Rs. ______ | Start: ________",
      "  5. H2 + C3 + O1 | Rs. ______ | Start: ________",
      "  6. H3 + C1 + O2 | Rs. ______ | Start: ________",
      "",
      "RESULTS",
      "  | # | CTR | CPL/CPA | ROAS | Kill/Scale/Iterate |",
      "  |---|-----|---------|------|-------------------|",
      "  | 1 |     |         |      |                   |",
      "  | 2 |     |         |      |                   |",
      "  | 3 |     |         |      |                   |",
      "  | 4 |     |         |      |                   |",
      "  | 5 |     |         |      |                   |",
      "  | 6 |     |         |      |                   |",
      "",
      "DECISION RULES",
      "  - Never judge under 3 days",
      "  - Kill the bottom half; double the top 1-2",
      "  - Iterate winners: one variable changed",
      "",
      "RULE: One variable per test, thresholds written",
      "before launch.",
    ],
  },
  {
    title: "Optimization Checklists",
    slug: "optimization-checklists",
    type: "pdf",
    description:
      "The weekly optimization ritual: review, decide, test, follow-up, learn — plus the diagnosis order.",
    sortOrder: 18,
    pdfLines: [
      "OPTIMIZATION CHECKLISTS",
      "ZetaGrow Pro Resource Library | File 18 of 40",
      "",
      "WEEKLY RITUAL",
      "MONDAY - REVIEW",
      "  [ ] KPIs vs last week (CTR, CPL, CPA, ROAS)",
      "  [ ] Spend vs plan",
      "  [ ] Creative ranking (best to worst)",
      "",
      "TUESDAY - DECIDE",
      "  [ ] Killed anything below threshold 5+ days",
      "  [ ] Budget +20-30% on top 1-2 performers",
      "",
      "WEDNESDAY - TEST",
      "  [ ] One new test launched (ONE variable)",
      "  [ ] Equal budgets per combo",
      "",
      "THURSDAY - FOLLOW-UP",
      "  [ ] Lead response speed verified",
      "  [ ] Landing page checked on mobile",
      "  [ ] Tracking events firing",
      "",
      "FRIDAY - LEARN",
      "  [ ] Learnings logged",
      "  [ ] Winner's hook noted for reuse",
      "  [ ] Next week's report drafted",
      "",
      "DIAGNOSIS ORDER (when failing)",
      "  1. Tracking real? -> 2. CTR low? (creative)",
      "  -> 3. No conversions? (page/offer)",
      "  -> 4. Costs high? (CPC/CPM/bidding)",
      "  -> 5. Frequency high? (fatigue)",
      "  -> 6. Economics broken? (LTV:CAC)",
      "",
      "RULE: Optimization is a weekly ritual, not an",
      "emergency response.",
    ],
  },
  // ── SEO (5) ─────────────────────────────────────────────────
  {
    title: "Keyword Research",
    slug: "keyword-research",
    type: "pdf",
    description:
      "Full keyword worksheet: intent classification, competitor keywords, long-tail goldmine, and priorities.",
    sortOrder: 19,
    pdfLines: [
      "KEYWORD RESEARCH",
      "ZetaGrow Pro Resource Library | File 19 of 40",
      "",
      "TOPIC: ______________________________",
      "",
      "KEYWORD TABLE",
      "  | Keyword | Intent I/C/T | Volume est. | Difficulty |",
      "  |---------|--------------|-------------|------------|",
      "  |         |              |             |            |",
      "  |         |              |             |            |",
      "  |         |              |             |            |",
      "  |         |              |             |            |",
      "",
      "COMPETITOR KEYWORDS (who ranks for what)",
      "  1. ______________________________",
      "  2. ______________________________",
      "  3. ______________________________",
      "",
      "LONG-TAIL GOLDMINE",
      "  1. ________________________________________",
      "  2. ________________________________________",
      "  3. ________________________________________",
      "  4. ________________________________________",
      "  5. ________________________________________",
      "",
      "INTENT KEY",
      "  I = Informational (articles)",
      "  C = Commercial (comparison + ads)",
      "  T = Transactional (product pages + ads)",
      "",
      "MONTHLY PRIORITIES",
      "  1. ________________ (content type: ________)",
      "  2. ________________ (content type: ________)",
      "  3. ________________ (content type: ________)",
      "",
      "RULE: Match content to intent. Long-tail first.",
    ],
  },
  {
    title: "SEO Planner",
    slug: "seo-planner",
    type: "pdf",
    description:
      "The content-cluster planner: pillar, supporting articles, internal links, on-page checklist, and refresh schedule.",
    sortOrder: 20,
    pdfLines: [
      "SEO PLANNER",
      "ZetaGrow Pro Resource Library | File 20 of 40",
      "",
      "CLUSTER TOPIC: ______________________________",
      "  Pillar URL: ______________________________",
      "  Pillar keyword: __________________________",
      "",
      "SUPPORTING ARTICLES (5-8)",
      "  1. Title: ________ | Keyword: ________ | Links: __",
      "  2. Title: ________ | Keyword: ________ | Links: __",
      "  3. Title: ________ | Keyword: ________ | Links: __",
      "  4. Title: ________ | Keyword: ________ | Links: __",
      "  5. Title: ________ | Keyword: ________ | Links: __",
      "",
      "INTERNAL LINKS",
      "  - Articles link UP to pillar [ ]",
      "  - Pillar links DOWN to articles [ ]",
      "  - 2+ internal links per article [ ]",
      "",
      "ON-PAGE CHECKLIST",
      "  [ ] Title (keyword first, <60 chars)",
      "  [ ] Meta description (155 chars, benefit + CTA)",
      "  [ ] One H1 + logical H2/H3",
      "  [ ] Keyword in first paragraph",
      "  [ ] Alt text with keyword variations",
      "",
      "CONTENT DEPTH RULES",
      "  - Answer the question completely",
      "  - Longer only if more value",
      "  - One cluster per month",
      "",
      "REFRESH SCHEDULE",
      "  Refresh top 20% of pages quarterly",
      "  Next refresh: ____________",
      "",
      "RULE: Depth beats volume; clusters build authority.",
    ],
  },
  {
    title: "Content Cluster Planner",
    slug: "content-cluster-planner",
    type: "pdf",
    description:
      "Map a full topic cluster with sub-topics, articles, keywords, linking structure, and publish order.",
    sortOrder: 21,
    pdfLines: [
      "CONTENT CLUSTER PLANNER",
      "ZetaGrow Pro Resource Library | File 21 of 40",
      "",
      "PILLAR TOPIC: ______________________________",
      "  URL: ________________________________",
      "  Keyword: ______________________________",
      "",
      "SUB-TOPIC 1: ______________________________",
      "  Articles + keywords:",
      "  - ________ | ________   - ________ | ________",
      "",
      "SUB-TOPIC 2: ______________________________",
      "  Articles + keywords:",
      "  - ________ | ________   - ________ | ________",
      "",
      "SUB-TOPIC 3: ______________________________",
      "  Articles + keywords:",
      "  - ________ | ________   - ________ | ________",
      "",
      "SUB-TOPIC 4: ______________________________",
      "  Articles + keywords:",
      "  - ________ | ________   - ________ | ________",
      "",
      "LINKING MAP",
      "  Pillar <-- A1  A2  A3",
      "  Pillar <-- B1  B2",
      "  Pillar <-- C1  C2  C3",
      "  (every article links UP to the pillar)",
      "",
      "PUBLISH ORDER (long-tail first)",
      "  1. ________  4. ________",
      "  2. ________  5. ________",
      "  3. ________  6. ________",
      "",
      "CONTENT FORMAT PER INTENT",
      "  I: guide/article | C: comparison/best-of",
      "  T: product page | Local: location pages",
      "",
      "RULE: One cluster per month. Own the topic, not",
      "just the keyword.",
    ],
  },
  {
    title: "SEO Audit Checklist",
    slug: "seo-audit-checklist",
    type: "pdf",
    description:
      "The full-site audit: crawlability, indexability, on-page, technical, links, local, and measurement.",
    sortOrder: 22,
    pdfLines: [
      "SEO AUDIT CHECKLIST",
      "ZetaGrow Pro Resource Library | File 22 of 40",
      "",
      "SITE: ______________________________  DATE: ____________",
      "",
      "CRAWLABILITY",
      "  [ ] XML sitemap submitted",
      "  [ ] robots.txt correct",
      "  [ ] No orphan pages",
      "  [ ] Clean URLs (no ?id=)",
      "",
      "INDEXABILITY",
      "  [ ] Canonical tags correct",
      "  [ ] No duplicate content",
      "  [ ] Structured data (products/articles/FAQ)",
      "",
      "ON-PAGE (per key page)",
      "  [ ] Title + meta with keywords",
      "  [ ] One H1 per page",
      "  [ ] Keywords in first paragraph",
      "  [ ] Alt text on images",
      "  [ ] 2+ internal links per page",
      "",
      "TECHNICAL",
      "  [ ] Mobile friendly",
      "  [ ] Fast (compress images, cache)",
      "  [ ] HTTPS",
      "",
      "LINKS",
      "  [ ] Quality backlinks (not bought)",
      "  [ ] Internal link equity to weak pages",
      "",
      "LOCAL (if local business)",
      "  [ ] GBP complete + verified",
      "  [ ] NAP consistent everywhere",
      "  [ ] Reviews requested + answered",
      "",
      "MEASUREMENT",
      "  [ ] Search Console connected",
      "  [ ] Impressions/clicks/position tracked",
      "  [ ] Quarterly refresh plan",
      "",
      "RULE: Fix crawlability and indexability before",
      "content. Audit quarterly.",
    ],
  },
  {
    title: "90-Day SEO Roadmap",
    slug: "90-day-seo-roadmap",
    type: "pdf",
    description:
      "The quarter plan: month 1 foundation, month 2 clusters, month 3 authority + measurement.",
    sortOrder: 23,
    pdfLines: [
      "90-DAY SEO ROADMAP",
      "ZetaGrow Pro Resource Library | File 23 of 40",
      "",
      "MONTH 1 - FOUNDATION",
      "  Week 1: Technical audit + fixes (sitemap, speed,",
      "          canonicals, structure)",
      "  Week 2: Keyword research + cluster 1 defined",
      "  Week 3: Search Console connected; baseline",
      "          impressions/clicks recorded",
      "  Week 4: Cluster 1: pillar + first 3 articles",
      "",
      "MONTH 2 - CLUSTERS",
      "  Week 5: Cluster 1 complete (5-8 articles, links)",
      "  Week 6: Cluster 2 defined + pillar published",
      "  Week 7: Cluster 2 articles (3)",
      "  Week 8: Cluster 2 complete; on-page fixes on",
      "          top pages; titles optimized",
      "",
      "MONTH 3 - AUTHORITY + MEASUREMENT",
      "  Week 9: Cluster 3 defined; linkable assets",
      "          (data, templates, case studies)",
      "  Week 10: Outreach for 3-5 quality backlinks",
      "  Week 11: Refresh top 20% of pages; add FAQ",
      "           structured data",
      "  Week 12: Review: impressions, clicks, positions,",
      "           winners; plan next quarter",
      "",
      "CHECKPOINTS",
      "  Monthly: Search Console trends",
      "  Quarterly: which pages rank for which keywords",
      "",
      "EXPECTATION",
      "  SEO compounds 6-18 months. Month 1-3 =",
      "  foundation; month 4+ = traffic growth.",
      "",
      "RULE: Consistency beats intensity. One cluster per",
      "month, measured weekly.",
    ],
  },
  // ── Sales (5) ───────────────────────────────────────────────
  {
    title: "Outreach Templates",
    slug: "outreach-templates",
    type: "pdf",
    description:
      "Cold and warm outreach formulas with fill-in blanks, plus follow-up outreach messages.",
    sortOrder: 24,
    pdfLines: [
      "OUTREACH TEMPLATES",
      "ZetaGrow Pro Resource Library | File 24 of 40",
      "",
      "COLD OUTREACH - FORMULA",
      "  Line 1: specific observation about THEM",
      "  Line 2: one reason you reached out",
      "  Line 3: low-friction ask",
      "",
      "TEMPLATE A",
      "  \"Hi [name], I noticed [their situation]. I help",
      "  [similar customers] with [outcome]. Can I share",
      "  how? [one link / 10-minute call].\"",
      "",
      "TEMPLATE B",
      "  \"Hi [name], [specific observation about their",
      "  business]. We recently did [result] for [similar",
      "  customer]. If useful, here is the case study:",
      "  [link]. No reply needed.\"",
      "",
      "TEMPLATE C (value first)",
      "  \"Hi [name], here is a [resource] I made for",
      "  [their situation]: [link]. Happy to discuss how",
      "  it applies to you.\"",
      "",
      "WARM OUTREACH",
      "  \"Hi [name], you asked about [X] on [post].",
      "  Here is what I know: [value]. Want me to walk",
      "  you through it?\"",
      "",
      "FOLLOW-UP (day 3, day 7)",
      "  \"Hi [name], circling back once - if the timing",
      "  is wrong, no problem. [One new value line].\"",
      "",
      "RULES",
      "  - Specific > generic; 20 targeted > 200 spammed",
      "  - One ask per message",
      "  - Never follow up more than 3 times",
      "",
      "RULE: Relevance is the only permission you have.",
    ],
  },
  {
    title: "Proposal Templates",
    slug: "proposal-templates",
    type: "pdf",
    description:
      "The one-page proposal structure: problem in their words, solution, investment, guarantee, next steps.",
    sortOrder: 25,
    pdfLines: [
      "PROPOSAL TEMPLATES",
      "ZetaGrow Pro Resource Library | File 25 of 40",
      "",
      "CLIENT: ______________________  DATE: ____________",
      "",
      "1. THE PROBLEM (their words, from discovery)",
      "  \"________________________________________\"",
      "",
      "2. THE GOAL",
      "  \"________________________________________\"  By: ________",
      "",
      "3. THE SOLUTION (package)",
      "  Deliverable 1: __________________________",
      "  Deliverable 2: __________________________",
      "  Deliverable 3: __________________________",
      "  Timeline: ______________________________",
      "",
      "4. THE INVESTMENT",
      "  Price: Rs. ______   Anchor: Rs. ______",
      "  Payment terms: __________________________",
      "",
      "5. THE GUARANTEE",
      "  ______________________________",
      "",
      "6. NEXT STEPS",
      "  1. You confirm by [date]",
      "  2. Agreement + payment link",
      "  3. Kickoff: [date]",
      "",
      "7. WHY US (proof)",
      "  ______________________________",
      "",
      "SEND RULES",
      "  - Same day as the call",
      "  - Follow-up: day 1, 3 (value), 7 (proof),",
      "    14 (decision)",
      "",
      "RULE: One page, their words, one next step.",
    ],
  },
  {
    title: "Sales Scripts",
    slug: "sales-scripts",
    type: "pdf",
    description:
      "Discovery call script, qualification gates, sales conversation structure, and the direct close.",
    sortOrder: 26,
    pdfLines: [
      "SALES SCRIPTS",
      "ZetaGrow Pro Resource Library | File 26 of 40",
      "",
      "PREP: lead source + their ask + likely problem",
      "",
      "1. OPEN (2 min)",
      "  \"Thanks for your time, [name]. To make this",
      "  useful - what are you trying to solve?\"",
      "",
      "2. SITUATION (3 min)",
      "  \"How does [task] work today? What have you",
      "  tried? What happened?\"",
      "",
      "3. PAST ATTEMPTS (3 min)",
      "  \"What did you spend on previous attempts?",
      "  What stopped them?\"",
      "",
      "4. COSTS (3 min)",
      "  \"What does this cost you in time, money,",
      "  and stress?\"",
      "",
      "5. OUTCOME (2 min)",
      "  \"If this worked perfectly, what would that",
      "  look like? By when?\"",
      "",
      "6. QUALIFY",
      "  Problem [ ]  Budget [ ]  Authority [ ]  Timing [ ]",
      "",
      "7. NEXT STEP",
      "  Qualified: \"Here is how I can help - shall I",
      "  send the proposal today?\"",
      "  Unqualified: \"Here is something useful anyway\"",
      "",
      "THE DIRECT CLOSE",
      "  \"Shall I send the payment link? I can start",
      "  today.\" (Then pause. Let them answer.)",
      "",
      "RULE: 70/30 listening. Their words become your",
      "proposal.",
    ],
  },
  {
    title: "Follow-up Scripts",
    slug: "follow-up-scripts",
    type: "pdf",
    description:
      "The 14-day follow-up sequence, stalled-deal reopeners, and re-engagement messages.",
    sortOrder: 27,
    pdfLines: [
      "FOLLOW-UP SCRIPTS",
      "ZetaGrow Pro Resource Library | File 27 of 40",
      "",
      "DAY 1 (same day as proposal)",
      "  \"Hi [name], here is your proposal: [link].",
      "  One thing to note: [differentiator]. Any",
      "  questions - I am available today.\"",
      "",
      "DAY 3 (add value)",
      "  \"Hi [name], thought this might help while you",
      "  decide: [useful resource]. No pressure.\"",
      "",
      "DAY 7 (proof)",
      "  \"Hi [name], here is a result from a similar",
      "  project: [case study]. It took [time] to get",
      "  [result]. Happy to walk you through it.\"",
      "",
      "DAY 14 (decision)",
      "  \"Hi [name], I don't want to keep this open",
      "  forever. If timing is wrong, tell me and I will",
      "  close the file. If it is right, I can start",
      "  [date] - the slot is open 48 hours.\"",
      "",
      "STALLED DEAL REOPENER",
      "  \"Since we last spoke, has anything changed with",
      "  [problem]? If it is still costing you [cost],",
      "  the offer stands until [date].\"",
      "",
      "NO-SHOW RESCHEDULE",
      "  \"Sorry we missed each other. Here are 2 slots",
      "  this week: [times]. Which works?\"",
      "",
      "RULE: Every follow-up adds value. Never just",
      "'checking in'.",
    ],
  },
  {
    title: "Objection Handling",
    slug: "objection-handling",
    type: "pdf",
    description:
      "The 5 biggest objections with response frameworks and a fill-in library of your own.",
    sortOrder: 28,
    pdfLines: [
      "OBJECTION HANDLING",
      "ZetaGrow Pro Resource Library | File 28 of 40",
      "",
      "1. \"TOO EXPENSIVE\"",
      "  Framework: compare to the cost of the problem.",
      "  \"Compared to what it costs you to not solve",
      "  this ([cost of problem]), [price] is [X]. The",
      "  guarantee removes the risk.\"",
      "",
      "2. \"I NEED TO THINK\"",
      "  Framework: find the missing clarity or trust.",
      "  \"Which part needs more clarity - the [A] or",
      "  the [B]? Let me address that specifically.\"",
      "",
      "3. \"NOT SURE IT WORKS FOR ME\"",
      "  Framework: exact-fit proof or a small first step.",
      "  \"Here is a case with someone in your exact",
      "  situation: [case]. Or start with [smaller",
      "  package] to prove it.\"",
      "",
      "4. \"NO TIME\"",
      "  Framework: make the effort explicit.",
      "  \"It takes [time commitment] per [period]. Here",
      "  is the first 30-minute step.\"",
      "",
      "5. \"LET ME ASK MY PARTNER\"",
      "  Framework: equip them to sell it.",
      "  \"Of course. Here is a one-page summary your",
      "  partner can read in 2 minutes: [link].\"",
      "",
      "YOUR OBJECTION LIBRARY",
      "  Objection 1: ________  Answer: ______________",
      "  Objection 2: ________  Answer: ______________",
      "  Objection 3: ________  Answer: ______________",
      "  Objection 4: ________  Answer: ______________",
      "  Objection 5: ________  Answer: ______________",
      "",
      "RULE: Objections are information, not rejection.",
    ],
  },
  // ── Operations (5) ──────────────────────────────────────────
  {
    title: "SOP Library",
    slug: "sop-library",
    type: "pdf",
    description:
      "The complete SOP template set: content, marketing, sales, onboarding, delivery, support, reporting, hiring, QC, finance.",
    sortOrder: 29,
    pdfLines: [
      "SOP LIBRARY",
      "ZetaGrow Pro Resource Library | File 29 of 40",
      "",
      "SOP FORMAT: task -> owner -> trigger -> steps",
      "-> tools -> done-when -> quality bar",
      "",
      "1. CONTENT SOP",
      "  Trigger: weekly planning. Steps: ideas -> pick 5",
      "  -> draft -> edit -> schedule -> repurpose.",
      "  Done: week scheduled with hooks/CTAs checked.",
      "",
      "2. MARKETING SOP",
      "  Trigger: launch. Steps: offer check -> page live",
      "  -> tracking -> matrix -> budget -> launch",
      "  -> diagnose day 3-5.",
      "  Done: running with review date + decision rules.",
      "",
      "3. SALES SOP",
      "  Trigger: new lead. Steps: capture -> score",
      "  -> route -> sequence -> proposal -> follow-ups",
      "  -> close -> handoff.",
      "  Done: every lead has status + next action.",
      "",
      "4. ONBOARDING SOP",
      "  Trigger: payment. Steps: welcome -> intake",
      "  -> kickoff -> plan approval -> milestone.",
      "  Done: onboarded in 48h with plan approved.",
      "",
      "5. DELIVERY SOP",
      "  Trigger: kickoff. Steps: brief -> draft -> QA",
      "  -> review -> revisions -> deliver -> feedback.",
      "  Done: delivered with summary + QA sign-off.",
      "",
      "6. SUPPORT SOP",
      "  Trigger: message. Steps: acknowledge -> classify",
      "  -> resolve/escalate -> log -> follow up.",
      "  Done: customer confirms resolution.",
      "",
      "7. REPORTING SOP",
      "  Trigger: weekly close. Steps: metrics vs",
      "  thresholds -> flags -> actions -> one-page report.",
      "  Done: report sent with fix list.",
      "",
      "8. HIRING SOP",
      "  Trigger: role needed. Steps: brief -> candidates",
      "  -> test task -> interview -> reference -> offer",
      "  -> onboarding.",
      "  Done: week 1 scheduled with training checklist.",
      "",
      "9. QUALITY CONTROL SOP",
      "  Trigger: before delivery. Steps: checklist",
      "  -> second pair of eyes -> approve.",
      "  Done: checklist signed off.",
      "",
      "10. FINANCE SOP",
      "  Trigger: weekly + monthly. Steps: revenue,",
      "  costs, margin, cash -> vs plan -> flags",
      "  -> decisions.",
      "  Done: numbers updated, one decision taken.",
      "",
      "RULE: Write each SOP after doing the task once.",
      "Run twice, fix, review quarterly.",
    ],
  },
  {
    title: "Client Onboarding",
    slug: "client-onboarding",
    type: "pdf",
    description:
      "The 5-step onboarding pipeline: welcome, intake, kickoff, plan approval, first milestone.",
    sortOrder: 30,
    pdfLines: [
      "CLIENT ONBOARDING",
      "ZetaGrow Pro Resource Library | File 30 of 40",
      "",
      "TRIGGER: Payment received / agreement signed.",
      "OWNER: Delivery lead.  TARGET: onboarded in 48h.",
      "",
      "STEP 1 - WELCOME (within 1 hour)",
      "  \"Welcome, [name]! Here is how everything works:",
      "  [links]. You will hear from us within 24 hours",
      "  with next steps.\"",
      "",
      "STEP 2 - INTAKE (same day)",
      "  Ask: goals, timeline, situation, examples,",
      "  contact preferences. Log in CRM.",
      "",
      "STEP 3 - KICKOFF CALL (within 48h)",
      "  Agenda: goals, scope, deliverables, timeline,",
      "  communication rules, first win.",
      "  Send notes + action items same day.",
      "",
      "STEP 4 - PLAN APPROVAL (same day as call)",
      "  Deliverables + dates + milestones + revision",
      "  limits. Client approves in writing.",
      "",
      "STEP 5 - FIRST MILESTONE",
      "  Date set: ____________",
      "",
      "DONE-WHEN",
      "  Access sent, plan approved, milestone dated,",
      "  expectations in writing.",
      "",
      "FAILURE MODES",
      "  - No intake response -> follow up twice, flag",
      "  - Vague goals -> call before any work",
      "",
      "RULE: Onboarding sets expectations; expectations",
      "set reviews.",
    ],
  },
  {
    title: "Project Management",
    slug: "project-management",
    type: "pdf",
    description:
      "The simple project system: board, owner, weekly update, revision tracking, and delivery checklist.",
    sortOrder: 31,
    pdfLines: [
      "PROJECT MANAGEMENT",
      "ZetaGrow Pro Resource Library | File 31 of 40",
      "",
      "PROJECT: ____________________  OWNER: ____________",
      "",
      "1. BOARD (simple: To-do | Doing | Review | Done)",
      "  To-do: ______________________________",
      "  Doing: ______________________________",
      "  Review: ______________________________",
      "  Done: ______________________________",
      "",
      "2. SCOPE (written at kickoff)",
      "  In scope: ______________________________",
      "  Out of scope: ______________________________",
      "  Revision limit: ______ rounds",
      "",
      "3. MILESTONES",
      "  1. ________ by ________  2. ________ by ________",
      "  3. ________ by ________",
      "",
      "4. WEEKLY CLIENT UPDATE",
      "  Done this week: ______________________",
      "  In progress: ______________________",
      "  Blocked by: ______________________",
      "  Next: ______________________",
      "",
      "5. CHANGE LOG",
      "  | Date | Change | Who |",
      "  |------|--------|-----|",
      "  |      |        |     |",
      "",
      "6. DELIVERY CHECKLIST",
      "  [ ] Files final  [ ] QA signed off",
      "  [ ] Summary written  [ ] Sent on time (early if",
      "      possible)",
      "",
      "RULE: Tools matter less than the rhythm.",
    ],
  },
  {
    title: "Reporting Templates",
    slug: "reporting-templates",
    type: "pdf",
    description:
      "Weekly one-page client report and monthly P&L: metrics, thresholds, flags, next actions.",
    sortOrder: 32,
    pdfLines: [
      "REPORTING TEMPLATES",
      "ZetaGrow Pro Resource Library | File 32 of 40",
      "",
      "WEEKLY ONE-PAGE REPORT",
      "  Client: ________  Period: ________ to ________",
      "",
      "  WHAT HAPPENED",
      "  - Deliverables: ______________________",
      "  - Milestones: ______________________",
      "",
      "  METRICS (vs thresholds)",
      "  CTR: ____%  CPL: Rs. ____  CPA: Rs. ____",
      "  ROAS: ____x  Leads: ____  Sales: ____",
      "  Flags: [ ] on track  [ ] fix needed",
      "",
      "  WHAT WE ARE FIXING",
      "  - ______________________________",
      "  - ______________________________",
      "",
      "  NEXT WEEK",
      "  - ______________________________",
      "",
      "MONTHLY P&L",
      "  Revenue: Rs. ________",
      "  Costs: fixed Rs. ____ + variable Rs. ____",
      "  Gross margin: ____%",
      "  CAC: Rs. ____  LTV: Rs. ____  LTV:CAC: ____x",
      "  Churn: ____%  Break-even check: [ ]",
      "  Profit: Rs. ________",
      "",
      "RULE: Reports exist to produce decisions, not",
      "to look busy.",
    ],
  },
  {
    title: "Quality-Control Checklists",
    slug: "quality-control-checklists",
    type: "pdf",
    description:
      "The pre-delivery QC checklist: facts, links, spelling, mobile, brand, second pair of eyes.",
    sortOrder: 33,
    pdfLines: [
      "QUALITY-CONTROL CHECKLISTS",
      "ZetaGrow Pro Resource Library | File 33 of 40",
      "",
      "DELIVERABLE: ________________  DATE: ____________",
      "",
      "FACTS & NUMBERS",
      "  [ ] All numbers verified",
      "  [ ] No invented claims",
      "  [ ] Prices/dates correct",
      "",
      "FILES & LINKS",
      "  [ ] Files open correctly",
      "  [ ] No broken links",
      "  [ ] Formats as promised",
      "",
      "WRITING",
      "  [ ] Spelling and grammar clean",
      "  [ ] Tone matches brand voice",
      "  [ ] No hype words",
      "",
      "VISUAL",
      "  [ ] Mobile view checked",
      "  [ ] Branding consistent",
      "  [ ] Images load fast",
      "",
      "SCOPE",
      "  [ ] Everything in scope delivered",
      "  [ ] Revision limit respected",
      "",
      "SECOND PAIR OF EYES",
      "  [ ] Reviewed by: ____________",
      "  [ ] Approved by: ____________",
      "",
      "FINAL",
      "  [ ] Summary written for client",
      "  [ ] Sent early if possible",
      "",
      "RULE: No checklist sign-off, no delivery.",
    ],
  },
  // ── AI (7) ──────────────────────────────────────────────────
  {
    title: "Advanced AI Prompts",
    slug: "advanced-ai-prompts",
    type: "pdf",
    description:
      "The master prompt library: research, marketing, sales, SEO, and operations prompt sets with review rules.",
    sortOrder: 34,
    pdfLines: [
      "ADVANCED AI PROMPTS",
      "ZetaGrow Pro Resource Library | File 34 of 40",
      "",
      "MASTER RULES (add to every prompt)",
      "  - \"Mark anything you are not certain about.\"",
      "  - \"Do not invent numbers or quotes.\"",
      "  - \"Use the material I provide, not general",
      "    knowledge.\"",
      "",
      "RESEARCH",
      "  \"Summarize these 20 reviews: top 5 pains in",
      "  the customers' own words, with counts.\"",
      "  \"Turn my interview notes into a problem",
      "  statement and 3 willingness-to-pay signals.\"",
      "",
      "MARKETING",
      "  \"Write 10 hooks about [topic] for [audience]:",
      "  curiosity, emotion, number, pattern interrupt.\"",
      "  \"Here is my winning ad: [copy]. Write 5",
      "  variations changing only the hook.\"",
      "",
      "SALES",
      "  \"From these call notes [notes], draft a",
      "  one-page proposal using the client's words.\"",
      "  \"Draft a day-3 follow-up that adds value",
      "  without pushing.\"",
      "",
      "SEO",
      "  \"Given these keywords [list], group them into",
      "  clusters by intent and suggest a pillar page",
      "  for each cluster.\"",
      "  \"Rewrite this title for CTR: keyword first,",
      "  under 60 characters, benefit-led.\"",
      "",
      "OPERATIONS",
      "  \"Turn these notes into an SOP: task, owner,",
      "  trigger, numbered steps, done-when.\"",
      "  \"Summarize this weekly data [data]: flag",
      "  anything above/below threshold, one action.\"",
      "",
      "REVIEW RULE",
      "  Every AI output passes human review before",
      "  reaching a customer or a decision.",
      "",
      "RULE: AI drafts 80%; you own the final 20%.",
    ],
  },
  {
    title: "AI Business Workflows",
    slug: "ai-business-workflows",
    type: "pdf",
    description:
      "The workflow pattern trigger→prompt→output→review applied to 8 business automations.",
    sortOrder: 35,
    pdfLines: [
      "AI BUSINESS WORKFLOWS",
      "ZetaGrow Pro Resource Library | File 35 of 40",
      "",
      "PATTERN: Trigger -> Prompt -> Output -> Review",
      "",
      "1. LEAD REPLY DRAFTING",
      "  Trigger: new lead form/WhatsApp.",
      "  Prompt: draft reply using their answers,",
      "  acknowledge specifics, one next step.",
      "  Review: human approves pre-approved template.",
      "",
      "2. LEAD SCORING",
      "  Trigger: form keywords.",
      "  Prompt: score fit/intent/timing (1-3 each),",
      "  recommend sales/nurture/newsletter.",
      "  Review: spot-check 10% weekly.",
      "",
      "3. SUPPORT REPLY DRAFTING",
      "  Trigger: known-topic ticket.",
      "  Prompt: reply using only our policy; flag",
      "  anything not covered.",
      "  Review: complex cases to human.",
      "",
      "4. DAILY REPORT SUMMARY",
      "  Trigger: end of day.",
      "  Prompt: summarize data, flag thresholds,",
      "  propose one action.",
      "  Review: Monday deep review.",
      "",
      "5. CONTENT REPURPOSING",
      "  Trigger: core piece published.",
      "  Prompt: cut into 5 shorts, 3 posts, 1 article,",
      "  1 email.",
      "  Review: edit into your voice.",
      "",
      "6. ONBOARDING MESSAGES",
      "  Trigger: payment received.",
      "  Prompt: draft welcome + quick-start using",
      "  purchase context.",
      "  Review: template approved once, reused.",
      "",
      "7. PROPOSAL DRAFTING",
      "  Trigger: discovery notes saved.",
      "  Prompt: one-page proposal in client's words.",
      "  Review: human checks promises + numbers.",
      "",
      "8. REVIEW/REFERRAL REQUESTS",
      "  Trigger: delivery + 7 days.",
      "  Prompt: personalize the ask with their",
      "  project result.",
      "  Review: spot-check 20%.",
      "",
      "RULE: Automate drafting, never judgment.",
    ],
  },
  {
    title: "Marketing Prompts",
    slug: "marketing-prompts",
    type: "pdf",
    description:
      "Ready-to-use prompts for strategy, campaigns, landing pages, funnels, and weekly marketing operations.",
    sortOrder: 36,
    pdfLines: [
      "MARKETING PROMPTS",
      "ZetaGrow Pro Resource Library | File 36 of 40",
      "",
      "STRATEGY",
      "  \"Build a one-page marketing strategy for",
      "  [offer] targeting [audience]: target, message,",
      "  channels, budget split, funnel, measurement.\"",
      "",
      "CAMPAIGNS",
      "  \"Plan a 30-day Meta campaign for [offer] at",
      "  Rs. [budget]: objective, audiences, budget",
      "  split, creative matrix, decision rules.\"",
      "",
      "LANDING PAGES",
      "  \"Draft a landing page for [offer]: headline,",
      "  subheadline, proof, problem, solution,",
      "  objections FAQ, offer, CTA. Benefit-led,\"",
      "",
      "FUNNELS",
      "  \"Design a [lead gen / e-commerce / creator /",
      "  service] funnel for [business]: stages, one",
      "  metric each, automation handoffs.\"",
      "",
      "WEEKLY OPS",
      "  \"Summarize this week's campaign data [data]:",
      "  vs thresholds, flags, one change to make.\"",
      "",
      "OFFER",
      "  \"Given my product [product], build 3 package",
      "  tiers with an upsell and a bundle, priced with",
      "  anchors.\"",
      "",
      "REVIEW RULES",
      "  - Check promises are deliverable",
      "  - Check numbers against real data",
      "  - Rewrite in your voice",
      "",
      "RULE: Give AI your real data; never a blank",
      "page.",
    ],
  },
  {
    title: "Sales Prompts",
    slug: "sales-prompts",
    type: "pdf",
    description:
      "Prompts for outreach, discovery, proposals, objection answers, and follow-ups — fed with client context.",
    sortOrder: 37,
    pdfLines: [
      "SALES PROMPTS",
      "ZetaGrow Pro Resource Library | File 37 of 40",
      "",
      "OUTREACH",
      "  \"Given this lead's profile [profile], write 3",
      "  cold outreach messages: specific observation,",
      "  reason, one ask. No hype.\"",
      "",
      "DISCOVERY",
      "  \"Write a 15-minute discovery script for a",
      "  [service] client with [situation]: situation,",
      "  past attempts, costs, outcome, qualify.\"",
      "",
      "PROPOSALS",
      "  \"From these discovery notes [notes], draft a",
      "  one-page proposal using the client's words:",
      "  problem, solution, investment, next steps.\"",
      "",
      "OBJECTIONS",
      "  \"The client said [objection]. Draft 2 honest",
      "  responses: one fact-based, one empathy-led.",
      "  No pressure tactics.\"",
      "",
      "FOLLOW-UPS",
      "  \"Draft follow-up 1/2/3 for [proposal context]:",
      "  day 3 value-add, day 7 proof, day 14 decision.",
      "  Each adds value.\"",
      "",
      "CLOSING",
      "  \"Draft a direct close message for a qualified",
      "  lead who has seen the proposal: one question,",
      "  clear next step.\"",
      "",
      "REVIEW RULES",
      "  - Never let AI promise discounts/policies",
      "  - Verify every number",
      "  - Human sends everything",
      "",
      "RULE: Personalization is the point; feed the AI",
      "real context.",
    ],
  },
  {
    title: "SEO Prompts",
    slug: "seo-prompts",
    type: "pdf",
    description:
      "Prompts for keyword research, clusters, titles/meta, content briefs, audits, and Search Console analysis.",
    sortOrder: 38,
    pdfLines: [
      "SEO PROMPTS",
      "ZetaGrow Pro Resource Library | File 38 of 40",
      "",
      "KEYWORD RESEARCH",
      "  \"Given my topic [topic], list 20 keywords with",
      "  intent (I/C/T) and 5 long-tail opportunities.",
      "  Mark uncertainty.\"",
      "",
      "CLUSTERS",
      "  \"Group these keywords [list] into 3 clusters",
      "  with a pillar topic each and 5 supporting",
      "  articles.\"",
      "",
      "TITLES & META",
      "  \"Rewrite this title for CTR: [current].",
      "  Keyword first, under 60 chars, benefit-led.",
      "  Then a 155-char meta description.\"",
      "",
      "CONTENT BRIEFS",
      "  \"Write a content brief for [keyword]: intent,",
      "  structure, sections, questions to answer,",
      "  internal links, CTA.\"",
      "",
      "ON-PAGE AUDIT",
      "  \"Audit this page against my checklist:",
      "  [paste page + checklist]. List only what",
      "  needs fixing, in priority order.\"",
      "",
      "SEARCH CONSOLE ANALYSIS",
      "  \"Here is my Search Console export [data].",
      "  Find pages with high impressions and low",
      "  clicks; recommend title fixes.\"",
      "",
      "FAQ GENERATION",
      "  \"From this article [text], write 5 FAQ",
      "  questions with short answers for schema.\"",
      "",
      "REVIEW RULES",
      "  - Verify facts, prices, dates",
      "  - Do not publish AI drafts unchanged",
      "",
      "RULE: AI drafts; you verify; Google ranks what",
      "is true.",
    ],
  },
  {
    title: "Research Prompts",
    slug: "research-prompts",
    type: "pdf",
    description:
      "Prompts for market research, competitor analysis, persona building, interviews, and pricing research.",
    sortOrder: 39,
    pdfLines: [
      "RESEARCH PROMPTS",
      "ZetaGrow Pro Resource Library | File 39 of 40",
      "",
      "MARKET RESEARCH",
      "  \"Given my niche [niche], list evidence of",
      "  demand (who pays, what they pay), market",
      "  structure, and growth signals. Mark anything",
      "  you are not certain about.\"",
      "",
      "COMPETITOR ANALYSIS",
      "  \"Here is my competitor data [data]. Map offer,",
      "  price, positioning, strengths, weaknesses for",
      "  each, then list 3 gaps I can own.\"",
      "",
      "PERSONA BUILDING",
      "  \"Build an ICP from these reviews/interviews",
      "  [material]: demographics, goals, surface/root/",
      "  emotional pains, objections, channels.\"",
      "",
      "INTERVIEW GUIDES",
      "  \"Write a 15-minute interview guide for",
      "  [problem]: warm-up, last attempt, costs,",
      "  desired outcome, willingness to pay.\"",
      "",
      "REVIEW MINING",
      "  \"From these 20 reviews [reviews]: top 5 pains",
      "  in customers' own words with counts, top 3",
      "  praises, top 3 complaints.\"",
      "",
      "PRICING RESEARCH",
      "  \"From this competitor pricing data [data]:",
      "  price ranges by tier, common anchors, gaps",
      "  I can exploit.\"",
      "",
      "SYNTHESIS",
      "  \"Turn all my research notes [notes] into a",
      "  one-page brief: problem statement, evidence,",
      "  offer angle, risks.\"",
      "",
      "REVIEW RULES",
      "  - Verify quotes against raw material",
      "  - No invented statistics",
      "",
      "RULE: Feed AI raw material; demand it stay",
      "grounded in it.",
    ],
  },
  {
    title: "Operations Prompts",
    slug: "operations-prompts",
    type: "pdf",
    description:
      "Prompts for SOP creation, reports, data analysis, support, onboarding, and workflow automation.",
    sortOrder: 40,
    pdfLines: [
      "OPERATIONS PROMPTS",
      "ZetaGrow Pro Resource Library | File 40 of 40",
      "",
      "SOP CREATION",
      "  \"Turn these notes into an SOP: task, owner,",
      "  trigger, numbered steps, tools, done-when,",
      "  quality bar, failure modes.\"",
      "",
      "WEEKLY REPORTS",
      "  \"Summarize this data [data] into a one-page",
      "  report: what happened, vs thresholds, flags,",
      "  next actions.\"",
      "",
      "DATA ANALYSIS",
      "  \"Here is my sales/marketing export [data].",
      "  Find patterns, anomalies, and segment",
      "  differences. Flag surprises for verification.\"",
      "",
      "CUSTOMER SUPPORT",
      "  \"Draft a support reply using only this policy",
      "  [policy] for [customer question]. If not",
      "  covered, say so and escalate.\"",
      "",
      "ONBOARDING",
      "  \"Draft the welcome + quick-start sequence for",
      "  a new [product] customer: 3 messages, one",
      "  goal each.\"",
      "",
      "WORKFLOW AUTOMATION",
      "  \"Design an automation for [task]: trigger,",
      "  prompt, output, human review step. Keep it",
      "  simple enough to build in a day.\"",
      "",
      "FINANCE REVIEW",
      "  \"From this P&L data [data]: margin, CAC, LTV,",
      "  churn, break-even check. Flag the one number",
      "  to fix first.\"",
      "",
      "REVIEW RULES",
      "  - AI output is a draft; humans decide",
      "  - Verify all numbers against source data",
      "",
      "RULE: Automate the drafting, never the",
      "judgment.",
    ],
  },
];